### ISSUE TITLE
unavco feedback 

### ISSUE THREAD

**Issue by dbekaert** [aria-tools/ARIA-tools#106]
**Unavco feedback**
@hfattahi @sssangha 
- Class initialization takes significant amount of time for example stacks, part of this should be able to parallelize this
- Have progress bar as its unclear if something is progressing.

**Comment by ehavazli** [comment]
I just created a pull request with the initial progress bar commit.

**Comment by dbekaert** [comment]
@ehavazli looks great, merged the PR.

**Comment by dbekaert** [comment]
We now have added the parallelization for the class too.
