### ISSUE TITLE
Setuptools entrypoints instead of scripts.

### ISSUE THREAD

**Issue by miili** [aria-tools/ARIA-tools#121]
Entry points to aria tools executables can be managed by distutils/setuptools,
`ariaExtract.py` or any other CLI will be placed into the correct `PATH` environment during installation.

Further the Python extension can be hidden, e.g. call `ariaExtract`.

https://setuptools.readthedocs.io/en/latest/setuptools.html#automatic-script-creation

**Comment by dbekaert** [comment]
Not sure i fully understand what you mean.
Could you provide some example or help with a PR?
