### ISSUE TITLE
setup_tools produces incorrect path

### ISSUE THREAD

**Issue by bbuzzanga** [aria-tools/ARIA-tools#125]
I'm installing on a linux machine with conda.
The shebang is not pointing to the correct python environment ;; except for the ariaTSsetup.py

For example, the **correct** first line in
`/home/bbuzz001/Miniconda3/envs/ARIA/lib/python3.7/bin/ariaTSsetup.py`

-  `#!/home/bbuzz001/Miniconda3/envs/ARIA/bin/python`

However the rest of the files (e.g. `.../ariaPlot.py`) have the _**incorrect**_ shebang:

- `#!/home/bbuzz001/Miniconda3/bin/python`

Any ideas?

**Comment by dbekaert** [comment]
Would remove the files in both locations and then run the setup.py again.
This just to make sure its not a legacy installation.
e.g. if you did not activate the environment first before running setup.py.

**Comment by bbuzzanga** [comment]
Thanks; I removed the files and had the same issue.
Reinstalling ARIA-tools entirely has fixed the problem though.
I think probably all I had to do was remove the `build` directory and rebuild using `setup.py`
