### ISSUE TITLE
2stage unwrapper

### ISSUE THREAD

**Issue by dbekaert** [aria-tools/ARIA-tools#133]
We now have an implementation for the two stage unwrapper on the **2stage branch**, with a 2stage_unittest.py added in the unittest folder. Variable results observed so far, but would like to open for more testing to the team, @rzinke, @bbuzz31, @sssangha, @ehavazli. Given caveats start with smaller region that has issues, but would avoid a fully decorelated area too.

## Install 
To get the code swap to a the 2stage branch first:
```
git checkout 2stage
```

Unlike the overlap stitching, the 2stage unwrapper requires **relaxIV**, which will be installed if found in thirdParty folder, but not distributed with ARIA-tools. You will need to download it prior to building ARIA-tools.
```
cd tools/thirdParty
git clone  https://github.com/frangio68/Min-Cost-Flow-Class.git
cd ../..
python setup build 
python setup install
```

To call the two stager use the "sm" or stitchmethod set to 2stage.
The verbose mode will make additional plots which will be useful for initial testing and maturation.
```
ariaExtract.py -f "products/*.nc" -sm 2stage -v
```

## Approach 
The two stage stitching consists out of two steps:
1) Stitching is performed on overlap of products, i.e. corrects for range shift and 2pi offset between largest overlapping connected component between two adjacent products. This is the current implementation for stitching and ensures that not a too large 2pi shift will occur between product transition for the merged product.
2) 2pi phase corrections are computed between connected components. This is where the new addition has been added.  This is adopted from what used to be done in ISCE, however with the main change that the approach uses polygon instead of raster operations. First the connected component edges are approximated by polygons, and pixels with minimum distance between connected components are kept. This is inputted into the 2stage minimization which uses triangulation and solves for minimum phase 2pi phase shift to make the network consistent. 

## Verbose mode
In verbose mode there will be:
- png figures generated for individual products (unwrapped phase and connected component folder). For example this is the connected component figure for two simualted products:
![Screen Shot 2020-02-19 at 4 10 10 PM](https://user-images.githubusercontent.com/19240905/74888262-58b5c880-5332-11ea-84ff-4abdb3c4fc18.png)

- For the first step (overlap) one should not expect the unwrapping errors to be fixed, rather there should be a path between two stitched products that is continuous (see the _intermediate png figure for the unwrapped folder). For example this is the intermediate phase result after stitching the two products:
![Screen Shot 2020-02-19 at 4 08 35 PM](https://user-images.githubusercontent.com/19240905/74888329-81d65900-5332-11ea-80a5-aff86b5e58cf.png)

- For the two stager there will be a folder "unwrap_2stagePlots" created which plots the minimum distance calculation between connected components (with size larger than a hard-coded value). An example is provided below: 
![1_2](https://user-images.githubusercontent.com/19240905/74888450-cfeb5c80-5332-11ea-8be7-ac061b08a47a.png)

- The minimum distances will be used as input for the two stage minimization problem. A figure summarizing the input to the function is stored as "inversion.png" with an example below:
![inversion](https://user-images.githubusercontent.com/19240905/74888513-fc9f7400-5332-11ea-9a0d-0faa2b4548b3.png)

- After the inversion is done a final unwrapped file and connected component file is written out in the corresponding folders. An example is provided here for the simulation.
![Screen Shot 2020-02-19 at 4 08 43 PM](https://user-images.githubusercontent.com/19240905/74888207-2d32de00-5332-11ea-80ee-99ef155e750a.png)

## Caveats
- The assumption is that products do not have unwrapping errors within their connected component. 
- The minimization is only done with a few pixels, i.e. its not using the shared edge between components. this means impact of noise to inversion.
- The approach does a minimization and wants to avoid adding large 2pi phase shifts.
- The existing approach is slow, but has room for speed-up but looking for some good test-cases to ensure the approach works.

**Comment by rzinke** [comment]
Hi @dbekaert, thanks for getting the 2stage unwrapper up and running. I have installed the components and I am testing it now...
For a baseline, I wanted to stitch my example data set with the "overlap" method. I used the command:

ariaExtract.py -w Overlap2015 -f "products2015/*.nc" -b '36.5 38.8 89.2 90.8' -d download -nt 8 -l "unwrappedPhase,coherence,amplitude" -sm overlap

But I get a strange set of error messages that look like this:
connIDMapping [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. -1.]
intMapping [-0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0.
 -0. -0. -0.  0.]
intShift [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
intShift [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
intShift [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
ERROR 1: /u/sar-r2/rzinke/Tibet/TwoStageTesting/ClosureMtns/IntermediateFiles_6wuwegcx/unw/Product_1_intShift.tif, band 1: Failed to compute min/max, no valid pixels found in sampling.
ERROR 1: /u/sar-r2/rzinke/Tibet/TwoStageTesting/ClosureMtns/IntermediateFiles_6wuwegcx/unw/Product_2_intShift.tif, band 1: Failed to compute min/max, no valid pixels found in sampling.
ERROR 1: /u/sar-r2/rzinke/Tibet/TwoStageTesting/ClosureMtns/IntermediateFiles_6wuwegcx/unw/Product_0_intShift.tif, band 1: Failed to compute min/max, no valid pixels found in sampling.
 
Generating: coherence - [==================================================] 20151214_20151027    0s /     0s
Generating: amplitude - [==================================================] 20151214_20151027    0s /     0s

Is this expected? It seems the resulting stitched interferograms look OK. 

Thanks,
Rob

**Comment by dbekaert** [comment]
@rzinke that is ok. The ERROR messages when making plots does not impact the result. The min and max are the same and the scale option in gdal translate to a png does not like that. The additional output is just for debug purposes, will eventually be removed. 

How does the intermediate result to the final result change?

**Comment by rzinke** [comment]
Hi @dbekaert, I understand about the PNG conversion (0-255) and the additional output for debugging. Thanks.

I am not sure I understand the question, "How does the intermediate result to the final result change?"

**Comment by dbekaert** [comment]
You can directly run the -sm 2stage. Per details above, the overlap method is run prior to two stage minimization. The figure with intermediate would be overlap result, while the one without would be the two stage result.

**Comment by rzinke** [comment]
When I run the 2stager I get the message:
Generating Connected Component polygons
...Done, loading polygons
outer valid
...Done
Traceback (most recent call last):
  File "/u/sar-r0/rzinke/python/miniconda3/envs/ARIA-tools/bin/ariaExtract.py", line 16, in <module>
    main(inps)
  File "/u/sar-r0/rzinke/python/miniconda3/envs/ARIA-tools/lib/python3.8/site-packages/ARIAtools/extractProduct.py", line 728, in main
    export_products(standardproduct_info.products[1], standardproduct_info.bbox_file, prods_TOTbbox, inps.layers, dem=demfile, lat=Latitude, lon=Longitude, mask=inps.mask, outDir=inps.workdir, outputFormat=inps.outputFormat, stitchMethodType=inps.stitchMethodType, verbose=inps.verbose, num_threads=inps.num_threads)
  File "/u/sar-r0/rzinke/python/miniconda3/envs/ARIA-tools/lib/python3.8/site-packages/ARIAtools/extractProduct.py", line 414, in export_products
    product_stitch_2stage(unw_files,conn_files,prod_bbox_files,bounds,prods_TOTbbox, outFileUnw=outFileUnw,outFileConnComp= outFileConnComp,mask=mask,outputFormat = outputFormat,verbose=verbose)
  File "/u/sar-r0/rzinke/python/miniconda3/envs/ARIA-tools/lib/python3.8/site-packages/ARIAtools/unwrapStitching.py", line 1920, in product_stitch_2stage
    unw.unwrapComponents()
  File "/u/sar-r0/rzinke/python/miniconda3/envs/ARIA-tools/lib/python3.8/site-packages/ARIAtools/unwrapStitching.py", line 580, in unwrapComponents
    self.__populatePointTablenew__()
  File "/u/sar-r0/rzinke/python/miniconda3/envs/ARIA-tools/lib/python3.8/site-packages/ARIAtools/unwrapStitching.py", line 645, in __populatePointTablenew__
    raise Exception("Nothing to do as all are from same connected component")
Exception: Nothing to do as all are from same connected component

I will find a different patch with more connected components and run again.

**Comment by dbekaert** [comment]
Currently does not support a single product, would try to add in a few. It only found like 2 polygons. Will add that capability in at some point.  Realistically should not error out just pass on.

**Comment by rzinke** [comment]
Okay, got it. I got an error "No module named pulp". I did conda install pulp, then had to rerun python3 setup.py build, install. Works now.

**Comment by rzinke** [comment]
The 2stage unwrapper seems to be struggling in some places. 
In the attached images, the top figure show the intermediate (overlap) ifgs...

![Intermediate](https://user-images.githubusercontent.com/48299159/74990346-e9a2a780-53f7-11ea-8af2-94a50e0ad303.png)

And the bottom shows the 2 stage ifgs

![2stage](https://user-images.githubusercontent.com/48299159/74990390-0c34c080-53f8-11ea-90b4-9dc13efc66e7.png)

Is some cases, it looks like the overlap method is functioning better

**Comment by rzinke** [comment]
It appears my image plotter does not always load images in the same order... In the above post, the image pairs for the overlap method are:
20151003_20150816_intermediate.vrt
20151120_20151027_intermediate.vrt
20151003_20150909_intermediate.vrt
20151214_20151027_intermediate.vrt
20151120_20151003_intermediate.vrt
20151027_20150909_intermediate.vrt
20151027_20151003_intermediate.vrt

And the image pairs for the 2stage method are:
20151027_20151003.vrt
20151120_20151003.vrt
20151003_20150816.vrt
20151003_20150909.vrt
20151120_20151027.vrt
20151214_20151027.vrt
20151027_20150909.vrt

So the order got somehow switched around.

**Comment by dbekaert** [comment]
@rzinke  It does not look like you have many unwrapping euros to start of with. So not great to see the two stager to introduce some errors. Could you share the download and extract line for the failed products you are testing?

The minimization is done based on a small window of point. We might need to control it as being a more qualitative set of points.

**Comment by dbekaert** [comment]
> Okay, got it. I got an error "No module named pulp". I did conda install pulp, then had to rerun python3 setup.py build, install. Works now.

Requirements have pulp included.

**Comment by dbekaert** [comment]
@piyushrpt do you have any thoughts for improving the correction. e.g. perhaps coherence?
