### ISSUE TITLE
Misclosure computation

### ISSUE THREAD

**Issue by rzinke** [aria-tools/ARIA-tools#135]
HOW IT WORKS
The code works by reading in a list of triplets and their date pairs, and from those:
1. Formulate a list of viable triplet combinations (IJ, JK, IK)
2. Subtract the reference point from those interferograms
3. Compute the disagreement based on IJ+JK-IK
... continue through the list of triplets. 

Both the misclosure values (positive or negative) and the absolute misclosure values (always positive) are computed and stored in 3D arrays, where each slice represents a triplet. The "cumulative" misclosure and absolute misclosure are computed by summing the 3D arrays. 

Once the (absolute) misclosure is calculated, the user can view the time history of any pixel by clicking on either map. 

EXAMPLES
[from a MintPy "inputs" directory]
computeCumMisclosure.py ifgramStack.h5 --exclude-pairs 20190103_20190115 20160530_20170724 20160530_20170618 20160530_20170606 20160530_20160810 -refX 38 -refY 212

[from an ARIA-tools "unwrappedPhase" directory]
computeCumMisclosure.py '*2017*.vrt' -refX 40 -refY 220 --plot-pairs

[from an ISCE stack "merged/interferograms" directory]
computeCumMisclosure.py '*' --print-files

ABOUT THE CODE
There is a lot of "book keeping" under the "Ancillary functions" section, because I was formerly calling those functions from another library. The essential code starts at the ###Data class section. 

POSSIBLE IMPROVEMENTS
I think the biggest place for improvement would be how the triplets are formulated. 

The reference point can be specified manually or automatically chosen. Currently, the reference point can only be given in pixel (radar) coordinates, not in geographic coordinates.

There should be an option to save the output data set in geographic or radar coordinates.

Here is the standalone version of the code (.py script attached as a .txt file for filter purposes). Please let me know if you have questions, comments, or requests:

[computeCumMisclosure.txt](https://github.com/aria-tools/ARIA-tools/files/4315805/computeCumMisclosure.txt)

**Comment by dbekaert** [comment]
@bbuzz31 @ehavazli could you give it a try over your subset regions?

**Comment by ehavazli** [comment]
Hi @rzinke,

Please consider the comments below. I wasn't able to run the code successfully so I can't really comment on the outputs or the workflow of the code. Please consider committing this piece of code to your branch and issue a pull request from there so we can discuss and work on the code using full github functionality.

Also  could you please clarify why we need a refX and refY to calculate the phase closure in a triplet?

- include example for each datatype structure in help (which you already provided in your message)
- line 740: 'is' and '==' swap is recommended by code by python 3.8 (no warning in python 3.7)
- "-t" or "--dataType" option returns "AssertionError"

**Comment by dbekaert** [comment]
@ehavazli There is no need to set a reference point when the interferograms
where generated from a coregistered stack.
For products that were generated pair-by-pair a reference would be needed.
However, could likely set it based on the average IFG too.

Agreed with on the idea of having this on a branch for testing and
integrated into set-up.py for rapid testing.

**Comment by bbuzzanga** [comment]
Running on my MintPy stack seems to have worked nicely, thanks @rzinke !.
Some issues/suggestions:

- I also can't get a result using ARIA results. There is the Assertion error that @ehavazli mentioned. And I can't get it to accept more than one .vrt.
- I think it might be a good idea for it to read a stack (i.e. from `ariaTSsetup.py`).
- Perhaps the exclude can include a boolean in case of MintPy, such that the dropIfgram data in the ifgramStack.h5 is used.
- I think you forgot to move over the 'viewingFunctions' method; it's currently undefined.
- Can you convert tabs to spaces as per PEP guidelines?

![Screen Shot 2020-03-25 at 19 46 22](https://user-images.githubusercontent.com/15522503/77596144-8e217900-6ed1-11ea-80d4-6cd0059b78ad.png)
![Screen Shot 2020-03-25 at 19 46 26](https://user-images.githubusercontent.com/15522503/77596146-8feb3c80-6ed1-11ea-9966-ad1f6d5b1292.png)
![Screen Shot 2020-03-25 at 19 46 38](https://user-images.githubusercontent.com/15522503/77596147-91b50000-6ed1-11ea-978b-a0ebb10b74fd.png)

**Comment by dbekaert** [comment]
@rzinke could you also provide some insight on how you would use this information in your analysis?

I would think some relevant statistics would be:
e.g. using the miss-closure to estimate bias on the velocity and velocity uncertainty, e.g. by assuming no displacements and only mis-closure.
e.g. an overview on how the average misclosure is for e.g. 6, 12, 24 XXXX days of IFG combination. This would provide more insight on what impact is of pairing strategy. 




I am not sure about the absolute variant.

**Comment by rzinke** [comment]
Hi all. Thanks for the helpful comments! These will improve the routine. I am modifying the code to incorporate several of them, and will move the code (and discussion) over to my fork of ARIA-tools in the next few hours.

**Comment by dbekaert** [comment]
@rzinke not sure this is still active and if you want to integrate into the repo?

**Comment by rzinke** [comment]
Yes, still active and I have some modifications in mind. I will make the modifications next week and resubmit the pull request.

**Comment by dbekaert** [comment]
PR was merged documentation was added. Will close this for now. Thanks @rzinke
