### ISSUE TITLE
trying to execute gdal_calc.py returns "The system cannot find the path specified."

### ISSUE THREAD

**Issue by CIoudy** [aria-tools/ARIA-tools#136]
everytime I try to execute: "`python gdal_calc.py -A "C:\Users\Username\GDAL\Python\unwrappedPhase\20190118_20190106.vrt" -B "C:\Users\Username\GDAL\Python\connectedComponents\20190118_20190106.vrt" --outfile "C:\Users\Username\GDAL\Python\results\20190118_20190106_defo" --calc='((A*(B>0))/(4*pi)*5.546576)' --format=ENVI --NoDataValue=0 --overwrite
`"
but running gdal_calc.py -h works.

I'm using anaconda3 with python3 in with win10 64bit.

**Comment by dbekaert** [comment]
I am wondering if this has to do with windows and path definition.
Can you show one of the paths in the vrt file as well?

**Comment by CIoudy** [comment]
so do you want the system path variables?

**Comment by dbekaert** [comment]
open the vrt file with a text reader and check the reported paths within
the file exist.
The vrt files are virtual files which point to other files on the system.

Also, did you process the files locally of did you copy them from somewhere
else?

**Comment by CIoudy** [comment]
I've opened the file and this is what I see:

```
<VRTDataset rasterXSize="3428" rasterYSize="2456">
  <SRS dataAxisToSRSAxisMapping="1,2">GEOGCS["GCS_unknown",DATUM["D_unnamed",SPHEROID["Spheroid",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["Degree",0.0174532925199433],AXIS["Longitude",EAST],AXIS["Latitude",NORTH]]</SRS>
  <GeoTransform>  3.4751036222630702e+01,  8.3339083762100201e-04, -0.0000000000000000e+00,  2.8185202248785700e+01, -0.0000000000000000e+00, -8.3327315149291504e-04</GeoTransform>
  <Metadata>
    <MDI key="Band_1">Band 1</MDI>
  </Metadata>
  <VRTRasterBand dataType="Float32" band="1">
    <NoDataValue>0</NoDataValue>
    <SimpleSource>
      <SourceFilename relativeToVRT="1">20190118_20190106</SourceFilename>
      <SourceBand>1</SourceBand>
      <SourceProperties RasterXSize="3428" RasterYSize="2456" DataType="Float32" BlockXSize="3428" BlockYSize="1" />
      <SrcRect xOff="0" yOff="0" xSize="3428" ySize="2456" />
      <DstRect xOff="0" yOff="0" xSize="3428" ySize="2456" />
    </SimpleSource>
  </VRTRasterBand>
</VRTDataset>


```

**Comment by CIoudy** [comment]
also, I did process the files locally in a directory named "GDAL" in D:\, but I've copied all the files to C:\ because I saw something on a form talking about putting the files from D:\ to C:\ while researching the problem.

**Comment by ehavazli** [comment]
@CIoudy @dbekaert 

I just ran a test with GDAL 3.0.1 and it worked

```
gdal_calc.py -A unwrappedPhase/20180122_20170103.vrt -B connectedComponents/20180122_20170103.vrt --outfile test_defo --calc='((A*(B>0))/(4*pi)*5.546576)' --format=ENVI --NoDataValue=0 --overwrite
```
I am not familiar with the windows handling of paths but the main difference I can see is the use of quotes in given paths.
Maybe removing the quotes from the paths can solve the problem.

**Comment by CIoudy** [comment]
I downloaded an ubuntu virtual machine and I'm currently setting up anaconda and gdal to see if it works. 
I tried changing the source code of "gdal_calc.py" and made it print "hello" before executing the main function but it still gave me the same results.

**Comment by ehavazli** [comment]
Please try running the command below and see if that works. GDAL possibly reads input files before running the main function.

```
python gdal_calc.py -A C:\Users\Username\GDAL\Python\unwrappedPhase\20190118_20190106.vrt -B C:\Users\Username\GDAL\Python\connectedComponents\20190118_20190106.vrt --outfile C:\Users\Username\GDAL\Python\results\20190118_20190106_defo --calc='((A*(B>0))/(4*pi)*5.546576)' --format=ENVI --NoDataValue=0 --overwrite
```

**Comment by CIoudy** [comment]
Unfortunately it didn't solve it.

**Comment by CIoudy** [comment]
Update: I removed the `--calc='((A*(B>0))/(4*pi)*5.546576)'` and executed without the Mysterious error.
But as soon as I add it back the Mysterious Error comes back.

**Comment by CIoudy** [comment]
Update: I replaced the quotation marks from ' > " and it didn't give me the Mysterious error! but it gave me this: `AttributeError: 'NoneType' object has no attribute 'SetGeoTransform'`

**Comment by CIoudy** [comment]
Update: I fixed it. I only changed the quotation marks from ' to " and changed the `outfile` to only `defo` and it worked!
