### ISSUE TITLE
Discontinuity in the azimuth angle (track-087)

### ISSUE THREAD

**Issue by yuankailiu** [aria-tools/ARIA-tools#137]
**Type:** Might be a Bug report
**About:** Extraction of imaging geometry layers: Discontinuity in the azimuth angle
**Tools**: ARIA-tools, MintPy

---

**Description of the problem**

After downloading the standard products from track-087 (ascending) in ARIA, I used MintPy to extract layers and prepared time-series analysis. [To load the ARIA interferograms into MintPy](https://nbviewer.jupyter.org/github/insarlab/MintPy-tutorial/blob/master/smallbaselineApp_aria.ipynb), I ran the `prep.py` command in MintPy. 

By running this command, the "inputs" directory inside the working directory is created, and two HDF5 files are produced. One of them is `geometryGeo.h5`, which contains geometrical datasets including incidence angle, azimuth angle, shadow layover mask, slant range distance, and height.

Then I plotted the geometry using MintPy command, `view.py`. Here is the figure, which shows a sharp discontinuity in the azimuth angle (parallel to the latitude). I think this is not expected behavior and maybe shows an issue somewhere?

![image](https://user-images.githubusercontent.com/55262505/78727203-de90d180-78e8-11ea-9587-64f65d36262d.png)

Below is a close look at the azimuth angle here (a weird jump at latitude~N27.2 degree):

![image](https://user-images.githubusercontent.com/55262505/78728944-97590f80-78ed-11ea-898e-4c3a166ac397.png)

I did the same procedure for track-160, but the azimuth angle looks fine.

![image](https://user-images.githubusercontent.com/55262505/78728527-6debb400-78ec-11ea-8cf1-69711d9121d3.png)

**Full code that generated the `geometryGeo.h5` file**

```
prep_aria.py -s ../ariaGUNW_087/stack/ -i ../ariaGUNW_087/incidenceAngle/20141023_20141011.vrt -d ../ariaGUNW_087/DEM/SRTM_3arcsec.dem -a ../ariaGUNW_087/azimuthAngle/20141023_20141011.vrt --water-mask ../ariaGUNW_087/mask/watermask.msk
```
.

**Full message after running this code**

```
extract metadata from /net/kraken/nobak/ykliu/Aqaba_processing/ariaGUNW_087/stack/unwrapStack.vrt
--------------------------------------------------
create HDF5 file /net/kraken/nobak/ykliu/Aqaba_processing/mintpy_A087/inputs/geometryGeo.h5 with w mode
create dataset: height                    of <class 'numpy.float32'>   in size of (8825, 4846)
create dataset: incidenceAngle            of <class 'numpy.float32'>   in size of (8825, 4846)
create dataset: slantRangeDistance        of <class 'numpy.float32'>   in size of (8825, 4846)
create dataset: azimuthAngle              of <class 'numpy.float32'>   in size of (8825, 4846)
create dataset: waterMask                 of <class 'numpy.bool_'>     in size of (8825, 4846)
close HDF5 file /net/kraken/nobak/ykliu/Aqaba_processing/mintpy_A087/inputs/geometryGeo.h5
--------------------------------------------------
writing data to HDF5 file /net/kraken/nobak/ykliu/Aqaba_processing/mintpy_A087/inputs/geometryGeo.h5 with a mode ...
finished writing to HD5 file: /net/kraken/nobak/ykliu/Aqaba_processing/mintpy_A087/inputs/geometryGeo.h5
--------------------------------------------------
```
.

**Full code that generated the figure from`geometryGeo.h5`**

```
view.py geometryGeo.h5 azimuthAngle
```

.

**Full message after running this code**

```
run view.py in MintPy release version v1.2.1-55, release date 2020-03-31
input file is geometry file: /net/kraken/nobak/ykliu/Aqaba_processing/mintpy_A087/inputs/geometryGeo.h5 in float32 format
file size in y/x: (8825, 4846)
num of datasets in file geometryGeo.h5: 5
datasets to exclude (0):
[]
datasets to display (1):
['azimuthAngle']
data   coverage in y/x: (0, 0, 4846, 8825)
subset coverage in y/x: (0, 0, 4846, 8825)
data   coverage in lat/lon: (33.557786178, 33.494166267, 37.596132434, 26.140117266999997)
subset coverage in lat/lon: (33.557786178, 33.494166267, 37.596132434, 26.140117266999997)
------------------------------------------------------------------------
colormap: jet
figure title: azimuthAngle
figure size : [5.49, 8.00]
reading data ...
data    range: [-260.8315, -258.11395] degree
display range: [-260.8315, -258.11395] degree
display data in transparency: 1.0
plot in Lat/Lon coordinate
map projection: PlateCarree
plotting image ...
plot scale bar: [0.2, 0.2, 0.1]
showing ...
```

**System information**

* Operating system: Linux server
* Version of Python: Python 3.7.3
* Version of ARIA-tools: *dev, up-to-date

**Comment by dbekaert** [comment]
Thanks for sharing, we will look into this. Azimuth angle should be vary smoothly.

**Comment by dbekaert** [comment]
@sssangha could you have a closer look into this. would be good to be fixed prior to the next release.

**Comment by ehavazli** [comment]
@liuykai I looked into track 87 data set and found that there is a problem with the azimuth angle when stitched together. We are working on identifying the step that causes this problem.

**Comment by dbekaert** [comment]
@liuykai @ehavazli  can you post the ariaTSprep command that was being used.

**Comment by ehavazli** [comment]
> @liuykai @ehavazli can you post the ariaTSprep command that was being used.

```
ariaExtract.py -f  './products/*.nc' -l azimuthAngle -d ./DEM/SRTM_SRTM_3arcsec.dem
```
I used ariaExtract.py to extract all the azimuth angle products because ariaTSsetup.py is extracting only the first date. Which looks like the image below

<img width="228" alt="image" src="https://user-images.githubusercontent.com/6526589/80140243-839fe100-855c-11ea-8d3e-ad1e46227935.png">

But there is also another case when the azimuth angle is just one value (as seen below):

<img width="254" alt="image" src="https://user-images.githubusercontent.com/6526589/80140390-b9dd6080-855c-11ea-8ce0-bd43a9c43ef0.png">

@sssangha can you comment on the extraction process?

**Comment by dbekaert** [comment]
Could you in addition also provide which products that have been used. Did you do a bulk pull of all track 87 products?

**Comment by dbekaert** [comment]
> I used ariaExtract.py to extract all the azimuth angle products because ariaTSsetup.py is extracting only the first date. Which looks like the image below

@ehavazli:
- are other extracted products do look ok, i.e. it is for two dates that there is a problem?
- I assume you did a bulk pull of all products on track 87?

**Comment by ehavazli** [comment]
> Could you in addition also provide which products that have been used. Did you do a bulk pull of all track 87 products?

I downloaded all the products and all the azimuth angle files are one or the other you see in my previous message.

**Comment by dbekaert** [comment]
# Simplification of the problem

## Single IFG with the problem:
```
ariaDownload.py -i 20151111_20150912 -t 87
ariaExtract.py -f "products/*.nc" -l 
gdal_translate -of png -scale azimuthAngle/20151111_20150912 azimuthAngle_all.png
```
** Output**
<details>
<img width="523" alt="Screen Shot 2020-04-23 at 2 43 13 PM" src="https://user-images.githubusercontent.com/19240905/80152573-c966a480-8570-11ea-9c88-6cc09f5a51ef.png">
</details>

## Investigating individual products:
statistical information for each product first band
Might be am internal product issue.
@sssangha  what do you think?

<details>

```
run6:Files: S1-GUNW-A-R-087-tops-20151111_20150912-154107-35000N_33121N-PP-59b3-v2_0_2.nc
STATISTICS_MINIMUM=-168.97549438477
STATISTICS_MAXIMUM=-168.63883972168

run5:Files: S1-GUNW-A-R-087-tops-20151111_20150912-154042-33509N_31626N-PP-d93a-v2_0_2.nc
STATISTICS_MINIMUM=-168.7850189209
STATISTICS_MAXIMUM=-168.47018432617

run4:Files: S1-GUNW-A-R-087-tops-20151111_20150912-154017-32015N_30131N-PP-7928-v2_0_2.nc
STATISTICS_MINIMUM=-168.60731506348
STATISTICS_MAXIMUM=-168.31510925293

run3:Files: S1-GUNW-A-R-087-tops-20151111_20150912-153952-30522N_28635N-PP-3c52-v2_0_2.nc
STATISTICS_MINIMUM=-168.44258117676
STATISTICS_MAXIMUM=-168.17669677734

run2:Files: S1-GUNW-A-R-087-tops-20151111_20150912-153927-29028N_26970N-PP-0a7b-v2_0_2.nc
STATISTICS_MINIMUM=-171.20016479492
STATISTICS_MAXIMUM=-170.70436096191

run1:Files: S1-GUNW-A-R-087-tops-20151111_20150912-153902-27533N_25472N-PP-153f-v2_0_2.nc
STATISTICS_MINIMUM=-170.92250061035
STATISTICS_MAXIMUM=-170.44570922852
```
</details>


## Where the data get computed in the products:
Meta-data cube code that is used to calculate the geometry information https://github.com/aria-jpl/ariamh/blob/develop/interferogram/sentinel/makeGeocube.py

How to call meta-data cube code (https://github.com/aria-jpl/ariamh/blob/593dfa6c90aea9ba7e9453e1207d54a00f9753c4/interferogram/sentinel/create_standard_product_s1.py#L1425):
```
makeGeocube.py -m master  -s slave -o metadata.h5
```

**Comment by sssangha** [comment]
@dbekaert @ehavazli, I was able to duplicate this issue. Very strange that the other interpolated metadata fields (e.g. incidence angles) look fine and smoothly vary. 

However, I've found that for the test case posed here with IFG "20151111_20150912", one of the frames "S1-GUNW-A-R-087-tops-20151111_20150912-153927-29028N_26970N-PP-0a7b-v2_0_2.nc" varies irregularly along azimuth:
<img width="1055" alt="Screen Shot 2020-04-24 at 2 21 11 AM" src="https://user-images.githubusercontent.com/13227405/80196870-c56b6e80-85d2-11ea-94b6-180e89006bd8.png">

while the others vary smoothly, e.g.:
<img width="1091" alt="Screen Shot 2020-04-24 at 2 19 45 AM" src="https://user-images.githubusercontent.com/13227405/80196889-cbf9e600-85d2-11ea-95bb-33d3788b4a72.png">

The former frame of course happens to be centered along this apparent discontinuity in the stitched azimuth field 

Also, when I only stitch the frames to the north, the azimuth angle varies smoothly. 

These observations--again, namely the fact that the other metadata layers vary smoothly and there is an irregularity along the azimuth angle layer in only one of the frames--leads me to believe that there is not a bug in the tools. So I am afraid this standard product frame field may be corrupted.

**Comment by ehavazli** [comment]
@sssangha Thank you for looking into the details. It looks like azimuth angle may be corrupted rather than the whole product. I generated time series and the phase or displacements don't show this jump. The problem is most likely with the azimuth angle layer only.

**Comment by dbekaert** [comment]
@ehavazli @liuykai 

As confirmed by @sssangha this is not an ARIA-tools bug that is introducing the artifact. But indicative of a bug in the meta-data cube generation during production. Which seems to be very consistent for that location. So far we have not encountered this in other products. We should have a closer look at the meta-data cube generation, as that is what is leveraged in production. Although the process for a fix will be slow. 
> Where the data get computed in the products:



For now, I suggest to either interpolate the azimuth angle to remove the jump or replace the azimuth angle with a uniform value. Either update the azimuthAngle/DATE file and re-run loading into MintPy (no need to re-run ariaTSprep as the stack files point virtually to the envi files), or directly update the azimuth variable within the MintPy geometry h5 file. @sssangha might have some bandwidth to code a stand-alone program for an interpolated fix, but a PR is welcomed to.

**Comment by ehavazli** [comment]
@dbekaert @liuykai 

azimuth angle problem doesn't affect the initial time series processing or results.

**Comment by yuankailiu** [comment]
@dbekaert @ehavazli   
I see. Thanks a lot. You are right, the azimuth angle issue doesn't have influences on the time-series results. I will keep it like this as for now. If I really do care about the azimuth angle in a later stage, I will interpolate the azimuth angle to remove the jump or just use a uniform value.

**Comment by dbekaert** [comment]
@ehavazli is right wrt time-series analysis.

Although, relevant if you want to do comparison with GPS or for modelling, where the azimuth angles is used for computing conversion factors from ENU to LOS.

**Comment by dbekaert** [comment]
@liuykai, thanks for reporting this. We need this sort of feedback to improve our products.

**Comment by yuankailiu** [comment]
@dbekaert @ehavazli @sssangha 
thank you all for testing.
