### ISSUE TITLE
Unittests excecuted during circleCI testing

### ISSUE THREAD

**Issue by dbekaert** [aria-tools/ARIA-tools#147]
# unit-test upon circleCI excecution 

Found that the cutting of a new release has been challenging.
We should add a set of basic unit test that gets executed with circleCI
See here for an example done by @leiyangleon for the RAiDER package
- https://github.com/leiyangleon/RAiDER/blob/dev/.circleci/config.yml.
- https://github.com/leiyangleon/RAiDER/tree/dev/test 

We started in the past with a cricleCI integration relying on docker, which we could just replace with the conda. We need to update the .circleci/config.yml file to run a set of test and build the code. We should include a test folder with the following test suite added. 

## Code build
We should build conda with support for:
- aria-Tools
- MintPy

## Testing of code install correctly:
<table class="tg">
  <tr>
    <th class="tg-yw4l"><b>Unit test count</b></th>
    <th class="tg-yw4l"><b>Program</b></th>
    <th class="tg-yw4l"><b>Test</b></th>
    <th class="tg-yw4l"><b>Outcome</b></th>
  </tr>
  <tr>
    <td class="tg-yw4l">1</td>
    <td class="tg-yw4l">test executable for ariaDownload, ariaExtract, ariaTSprep,</td>
    <td class="tg-yw4l">e.g.; ariaDownload.py -h</td>
    <td class="tg-yw4l">provide help not error out</td>
  </tr>
  <tr>
    <td class="tg-yw4l">2</td>
    <td class="tg-yw4l">test executable for MintPY</td>
    <td class="tg-yw4l">prep_aria.py -h</td>
    <td class="tg-yw4l">provide help not error out</td>
  </tr>
</table>

## Testing of code runs:

<table class="tg">
  <tr>
    <th class="tg-yw4l"><b>Unit test count</b></th>
    <th class="tg-yw4l"><b>Program</b></th>
    <th class="tg-yw4l"><b>Test</b></th>
    <th class="tg-yw4l"><b>Outcome</b></th>
  </tr>
  <tr>
    <td class="tg-yw4l">1</td>
    <td class="tg-yw4l">product count</td>
    <td class="tg-yw4l">ariaDownload.py -t 124 -w products --ifg 20180408_20180502 -v -o count </td>
    <td class="tg-yw4l">2 </td>
  </tr>
  <tr>
    <td class="tg-yw4l">2</td>
    <td class="tg-yw4l">product url</td>
    <td class="tg-yw4l">ariaDownload.py -t 124 -w products --ifg 20180408_20180502 -v -o url    </td>       
   <td class="tg-yw4l">file: products/download_products_1240.txt </td>
  </tr>

  <tr>
    <td class="tg-yw4l">3</td>
    <td class="tg-yw4l">product download </td>
    <td class="tg-yw4l">ariaDownload.py -t 124 -w products --ifg 20180408_20180502 -v   </td>       
   <td class="tg-yw4l"> 2 products in: products/*.nc </td>
  </tr>

  <tr>
    <td class="tg-yw4l">4</td>
    <td class="tg-yw4l">extract of 3D data</td>
    <td class="tg-yw4l">ariaExtract.py -f "products/*.nc"  -l azimuthAngle -d download </td>       
   <td class="tg-yw4l">file: azimuthAngle/20180502_20180408 </td>
  </tr>

  <tr>
    <td class="tg-yw4l">5</td>
    <td class="tg-yw4l">extract of mosaic data</td>
    <td class="tg-yw4l">ariaExtract.py -f "products/*.nc"  -l coherence </td>       
   <td class="tg-yw4l">file: coherence/20180502_20180408 </td>
  </tr>

  <tr>
    <td class="tg-yw4l">6</td>
    <td class="tg-yw4l">extract of unwrapped data - overlap</td>
    <td class="tg-yw4l">ariaExtract.py -f "products/*.nc"  -l coherence </td>       
   <td class="tg-yw4l">file: coherence/20180502_20180408.vrt </td>
  </tr>

  <tr>
    <td class="tg-yw4l">7</td>
    <td class="tg-yw4l">extract of unwrapped data - overlap</td>
    <td class="tg-yw4l">ariaExtract.py -f "products/*.nc"  -l unwrappedPhase </td>       
   <td class="tg-yw4l">file: unwrappedPhase/20180502_20180408 </td>
  </tr>

  <tr>
    <td class="tg-yw4l">8</td>
    <td class="tg-yw4l">tsprep</td>
    <td class="tg-yw4l">ariaTSsetup.py -d download -m download -f "products/*.nc" </td>       
   <td class="tg-yw4l"> 3 files under stack folder: stack/cohStack.vrt; stack/connCompStack.vrt; stack/unwrapStack.vrt</td>
  </tr>

  <tr>
    <td class="tg-yw4l">9</td>
    <td class="tg-yw4l">run loading of aria products in mintpy</td>
    <td class="tg-yw4l">prep_aria.py -w mintpy -s stack/ -d DEM/SRTM_3arcsec.dem -i incidenceAngle/20180502_20180408.vrt -a azimuthAngle/20180502_20180408.vrt --water-mask mask/watermask.msk </td>       
   <td class="tg-yw4l">h5 files in mintpy/input folder </td>
  </tr>
</table>

**Comment by sssangha** [comment]
@yunjunz I am trying to implement unit-tests for "prep_aria.py" as so: 
```prep_aria.py -d ../DEM/SRTM_3arcsec.dem -i ../incidenceAngle/20151111_20150912.vrt -a ../azimuthAngle/20151111_20150912.vrt -s ../stack```

But I encounter the following error message:
```Traceback (most recent call last):
  File "/data2/ssangha/conda_installation/stable_feb14_2020/MintPy/mintpy/prep_aria.py", line 533, in <module>
    main()
  File "/data2/ssangha/conda_installation/stable_feb14_2020/MintPy/mintpy/prep_aria.py", line 465, in main
    inps = cmd_line_parse(iargs)
  File "/data2/ssangha/conda_installation/stable_feb14_2020/MintPy/mintpy/prep_aria.py", line 125, in cmd_line_parse
    fnames = glob.glob(fname)
  File "/data2/ssangha/conda_installation/stable_feb14_2020/envs/ARIA-tools/lib/python3.6/glob.py", line 20, in glob
    return list(iglob(pathname, recursive=recursive))
  File "/data2/ssangha/conda_installation/stable_feb14_2020/envs/ARIA-tools/lib/python3.6/glob.py", line 40, in _iglob
    dirname, basename = os.path.split(pathname)
  File "/data2/ssangha/conda_installation/stable_feb14_2020/envs/ARIA-tools/lib/python3.6/posixpath.py", line 107, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

Can you please advice me here? I think I just may not be calling "prep_aria.py" appropriately.

**Comment by yunjunz** [comment]
Hi @sssangha, I guess this is a bug we introduced during the last update. Could you try to change [prep_aria.py#L125](https://github.com/insarlab/MintPy/blob/master/mintpy/prep_aria.py#L125) from:

```
fnames = glob.glob(fname)
```

to 

```
if fname:
    fnames = glob.glob(fname)
else:
    fnames = []
```

**Comment by sssangha** [comment]
@yunjunz thanks, this works now!

I will have to change the part where the nodata values are parsed as it tries to get these values from the second IFG in the stack. 

E.g. since we only pass one IFG in these unit tests, it errors out when trying to index "dsUnw.GetFileList()[2]". This is fixed when I change this to "dsUnw.GetFileList()[-1]".

I will issue a PR to address this. 

Thanks again!

**Comment by yunjunz** [comment]
Hi @bbuzz31, I randomly chose `2` instead of `0` or `-1` in https://github.com/insarlab/MintPy/pull/155, apparently for no reason. Your fix sounds good to me!

**Comment by dbekaert** [comment]
@yunjunz @sssangha ok great, the circleCI test pass through till the last test. That should pass as well once the PR is updated https://github.com/insarlab/MintPy/pull/329

Closing this issue.
