### ISSUE TITLE
Ensuring raster sizes are the same

### ISSUE THREAD

**Issue by rzinke** [aria-tools/ARIA-tools#148]
I have been reprocessing some data and I ran into an error related to the size of the rasters from ariaExtract. Specifically, when I run:
ariaExtract.py -w Extracted -f "products/*.nc" -d download -m download -croptounion -l all

I get the error:
Generating: bPerpendicular - [>                                                 ]Traceback (most recent call last):
  File "/u/sar-r0/rzinke/python/miniconda3/envs/ARIA-tools/bin/ariaExtract.py", line 16, in <module>
    main(inps)
  File "/u/sar-r0/rzinke/python/miniconda3/envs/ARIA-tools/lib/python3.6/site-packages/ARIAtools/extractProduct.py", line 757, in main
    export_products(standardproduct_info.products[1], standardproduct_info.bbox_file, prods_TOTbbox, inps.layers, inps.rankedResampling, dem=demfile, lat=Latitude, lon=Longitude, mask=inps.mask, outDir=inps.workdir, outputFormat=inps.outputFormat, stitchMethodType='overlap', verbose=inps.verbose, num_threads=inps.num_threads, multilooking=inps.multilooking)
  File "/u/sar-r0/rzinke/python/miniconda3/envs/ARIA-tools/lib/python3.6/site-packages/ARIAtools/extractProduct.py", line 396, in export_products
    finalize_metadata(outname, open_shapefile(bbox_file, 0, 0).bounds, prods_TOTbbox, dem, lat, lon, mask, outputFormat, verbose=verbose)
  File "/u/sar-r0/rzinke/python/miniconda3/envs/ARIA-tools/lib/python3.6/site-packages/ARIAtools/extractProduct.py", line 501, in finalize_metadata
    out_interpolated = mask.ReadAsArray()*out_interpolated
ValueError: operands could not be broadcast together with shapes (18481,7476) (18481,7477)

So it appears that when aria-tools resamples the data it does not ensure that all rasters (in this case the bPerpendicular) are the same size. Would you like me to try to build this fix in by specifying the array size?

**Comment by sssangha** [comment]
@rzinke, hmm strange, I thought I had resolved this inconsistency a while back. Which revision is this though? Can you try again with my latest PR #145? 

If this issue persists with the latest PR, could you provide me with a list of products you had used so I can try to duplicate it?

**Comment by EJFielding** [comment]
Nicola was having some similar trouble a few weeks ago when he tried to use a small bounding box. It worked fine when he used a bigger box. I was not sure if it was an ARIA-tools bug or pilot error. I will ask him to try that again when this is merged in to the main version. I think it is a little complicated to explain how he could run the PR version.

**Comment by dbekaert** [comment]
The only difference is to clone from the PR instead of the dev branch.
The install procedure remains the same.

**Comment by rzinke** [comment]
Hi @sssangha, I have installed the sss_bugfixes version of ARIA-tools and am rerunning some of the test patches. Track 41 works fine, but track 121 is throwing an unexpected error. Have you encountered anything similar?

For the command:
ariaExtract.py -f "/u/sar-r2/rzinke/Tibet/Track121/AllProducts/*2017*.nc" -d download -m download -l all -nt 8 -w T121 -croptounion

I get the error:
All (314) interferograms are spatially continuous.
All layers are to be extracted, pass all keys.
Thread count specified for gdal multiprocessing = 8
Traceback (most recent call last):
  File "/u/sar-r0/rzinke/python/miniconda3/envs/ARIA-tools/bin/ariaExtract.py", line 16, in <module>
    main(inps)
  File "/u/sar-r0/rzinke/python/miniconda3/envs/ARIA-tools/lib/python3.6/site-packages/ARIAtools/extractProduct.py", line 743, in main
    standardproduct_info.products[0], standardproduct_info.products[1], standardproduct_info.bbox_file, prods_TOTbbox, arrshape, proj = merged_productbbox(standardproduct_info.products[0], standardproduct_info.products[1], os.path.join(inps.workdir,'productBoundingBox'), standardproduct_info.bbox_file, inps.croptounion, num_threads=inps.num_threads, minimumOverlap=inps.minimumOverlap)
  File "/u/sar-r0/rzinke/python/miniconda3/envs/ARIA-tools/lib/python3.6/site-packages/ARIAtools/extractProduct.py", line 281, in merged_productbbox
    union_bbox=open_shapefile(outname, 0, 0)
  File "/u/sar-r0/rzinke/python/miniconda3/envs/ARIA-tools/lib/python3.6/site-packages/ARIAtools/shapefile_util.py", line 37, in open_shapefile
    file_bbox = file_bbox.GetLayerByIndex(lyrind).GetFeature(ftind)
AttributeError: 'NoneType' object has no attribute 'GetLayerByIndex'

**Comment by dbekaert** [comment]
@rzinke would recommend to test wrt the dev branch as there are no open PR from @sssangha  at the moment which are note yet merge. To my knowledge this issue has also not been fixed on the dev branch either, nor release 1.1, but we know how to fix it.

Not sure if you missed a wild-card in your command.

**Comment by rzinke** [comment]
I copied the wrong command, I had been running "/u/sar-r2/rzinke/Tibet/Track121/AllProducts/*2017*.nc" with wildcards. 

Switching to branch dev and retesting.

**Comment by dbekaert** [comment]
I have seen something like this if one of the files got corrupted or if i was running from a non-cleaned directory.

**Comment by sssangha** [comment]
@rzinke, yes I'd recommend to test in a clean directory as @dbekaert said. In case the products themselves were corrupted (i.e. the download had been interrupted), I'd save some time and just redownload a small subset in time and run a test on that.

**Comment by rzinke** [comment]
Thanks for the suggestions. Re-running after clearing the old directory seems to have solved the error "...AttributeError: 'NoneType' object has no attribute 'GetLayerByIndex'"

However, I am still receiving the error I first reported pertaining to the incorrect raster size, i.e., 
Generating: bPerpendicular - [>                                                 ]Traceback (most recent call last):
  File "/u/sar-r0/rzinke/python/miniconda3/envs/ARIA-tools/bin/ariaExtract.py", line 16, in <module>
    main(inps)
  File "/u/sar-r0/rzinke/python/miniconda3/envs/ARIA-tools/lib/python3.6/site-packages/ARIAtools/extractProduct.py", line 757, in main
    export_products(standardproduct_info.products[1], standardproduct_info.bbox_file, prods_TOTbbox, inps.layers, inps.rankedResampling, dem=demfile, lat=Latitude, lon=Longitude, mask=inps.mask, outDir=inps.workdir, outputFormat=inps.outputFormat, stitchMethodType='overlap', verbose=inps.verbose, num_threads=inps.num_threads, multilooking=inps.multilooking)
  File "/u/sar-r0/rzinke/python/miniconda3/envs/ARIA-tools/lib/python3.6/site-packages/ARIAtools/extractProduct.py", line 396, in export_products
    finalize_metadata(outname, open_shapefile(bbox_file, 0, 0).bounds, prods_TOTbbox, dem, lat, lon, mask, outputFormat, verbose=verbose)
  File "/u/sar-r0/rzinke/python/miniconda3/envs/ARIA-tools/lib/python3.6/site-packages/ARIAtools/extractProduct.py", line 501, in finalize_metadata
    out_interpolated = mask.ReadAsArray()*out_interpolated
ValueError: operands could not be broadcast together with shapes (18481,7476) (18481,7477)

**Comment by sssangha** [comment]
@EJFielding, I have addressed this issue now in the latest PR #156, so I'd suggest you and/or Nicola take a look.

**Comment by dbekaert** [comment]
Closing this ticket as it is resolved for @rzinke . However need to confirm that #157 is resolved too.
