### ISSUE TITLE
Ionosphere included in "all" layers

### ISSUE THREAD

**Issue by rzinke** [aria-tools/ARIA-tools#149]
When I use ariaExtract and specify the layers as "all" I get an error that the ionosphere layer is not detected. This makes sense since no ionospheric corrections were made. Should the ionosphere layer be included as a standard layer in the list of "all" layers?

**Comment by sssangha** [comment]
@rzinke, I had fixed this in my latest PR #145. Specifically, I removed the hardcoded ionospheric layer key as it doesn't exist in the current standard product versions.

**Comment by dbekaert** [comment]
@rzinke this should have been resolved in the pre-release of v1.1. 
Can you give it a go. Currently 1.1 is the same as the dev branch.

**Comment by rzinke** [comment]
This worked with the most recent updates: The ionosphere error is gone. Thanks.

**Comment by dbekaert** [comment]
thanks for confirming. closing the issue as its solved based with all the fixes under version 1.1
