### ISSUE TITLE
Rounding/ float error when doing interpolation to extract incidence angle

### ISSUE THREAD

**Issue by cheryltwj** [aria-tools/ARIA-tools#165]
Hi developers, I encountered this error when running ARIA Tools for standard displacement products over Kuala Lumpur, during the extraction of incidence angle for the first interferogram:
```
Extracting single incidence angle, look angle and azimuth angle files valid over common interferometric grid
Generating: incidenceAngle - [==================================================] 20150328_20150304Traceback (most recent call last):
  File "/opt/conda/envs/ARIA-tools/bin/ariaTSsetup.py", line 15, in <module>
    main(inps)
  File "/opt/conda/envs/ARIA-tools/lib/python3.8/site-packages/ARIAtools/tsSetup.py", line 271, in main
    export_products([dict(zip([k for k in set(k for d in standardproduct_info.products[1] for k in d)], [[item for sublist in [list(set(d[k])) for d in standardproduct_info.products[1] if k in d] for item in sublist] for k in set(k for d in standardproduct_info.products[1] for k in d)]))], standardproduct_info.bbox_file, prods_TOTbbox, layers, dem=demfile, lat=Latitude, lon=Longitude, mask=inps.mask, outDir=inps.workdir, outputFormat=inps.outputFormat, stitchMethodType='overlap', verbose=inps.verbose, num_threads=inps.num_threads, multilooking=inps.multilooking)
  File "/opt/conda/envs/ARIA-tools/lib/python3.8/site-packages/ARIAtools/extractProduct.py", line 396, in export_products
    finalize_metadata(outname, open_shapefile(bbox_file, 0, 0).bounds, prods_TOTbbox, dem, lat, lon, mask, outputFormat, verbose=verbose)
  File "/opt/conda/envs/ARIA-tools/lib/python3.8/site-packages/ARIAtools/extractProduct.py", line 490, in finalize_metadata
    out_interpolated = interpolator(np.stack((np.flip(dem.ReadAsArray(), axis=0), lat, lon), axis=-1))
  File "/opt/conda/envs/ARIA-tools/lib/python3.8/site-packages/scipy/interpolate/interpolate.py", line 2486, in __call__
    raise ValueError("One of the requested xi is out of bounds "
ValueError: One of the requested xi is out of bounds in dimension 1
```

DEM was by default downloaded via ARIA Tools (did not specify my own). I checked that gdalinfo shows consistent metadata between the DEM and interferograms. The error seems related to the interpolation of DEM/ lat/ lon and the latitude is out of bounds? When tracing back to scipy's interpolate.py, this looks like it may be due to the rounding of floating points (https://github.com/scipy/scipy/blob/master/scipy/interpolate/interpolate.py#L2484-L2489), where:
self.grid[i][0] = 2.0920806208778604 (from interferogram)
p[-1]              = 2.09208062087786 (from xi --> DEM)

I have attached the logs for this error, a bash script to download the Kuala Lumpur standard products from our ARIA-SG AWS S3 bucket, and a .json bbox for running ariaTSsetup.py. The ARIA Tools version used is as of this commit: https://github.com/aria-tools/ARIA-tools/commit/a9de4fc5e7bda8dff04f6056ff7c43a7f8e6bfa5. Commands ran:
```
bash ./wget_script.bash
mv ./S1-GUNW* products
ariaTSsetup.py -f './products/S1-GUNW*/*.nc' -b ./P091_KualaLumpur_1133.json -d Download --mask Download
```
[KualaLumpur.zip](https://github.com/aria-tools/ARIA-tools/files/4607525/KualaLumpur.zip)

Thank you!

**Comment by sssangha** [comment]
@cheryltwj it looks like your commit is slightly outdated. One of the successive commits actually made some improvements to the interpolation procedure. 

So try commit cc947e3, the latest commit as of this writing.

**Comment by cheryltwj** [comment]
Thanks @sssangha! The latest commit https://github.com/aria-tools/ARIA-tools/commit/cc947e3697f5b016aa15aa3f14d5a71196c97207 did resolve the issue.

**Comment by cheryltwj** [comment]
@sssangha Sorry, I just noticed this after running MintPy with the ARIA Tools outputs generated with this latest commit:

In the incidenceAngle, lookAngle and azimuthAngle folders, the sizes of the data file and its corresponding .vrt file do not match. For example data file of incidenceAngle:
```
$ gdalinfo 20150328_20150304
Driver: ENVI/ENVI .hdr Labelled
Files: 20150328_20150304
    20150328_20150304.aux.xml
    20150328_20150304.hdr
Size is 2485, 2230
Coordinate System is:
GEOGCRS["GCS_unknown",
  DATUM["D_unnamed",
    ELLIPSOID["Spheroid",6378137,298.257223563,
      LENGTHUNIT["metre",1,
        ID["EPSG",9001]]]],
  PRIMEM["Greenwich",0,
    ANGLEUNIT["Degree",0.0174532925199433]],
  CS[ellipsoidal,2],
    AXIS["longitude",east,
      ORDER[1],
      ANGLEUNIT["Degree",0.0174532925199433]],
    AXIS["latitude",north,
      ORDER[2],
      ANGLEUNIT["Degree",0.0174532925199433]]]
Data axis to CRS axis mapping: 1,2
Origin = (100.971173964038002,3.950219073141480)
Pixel Size = (0.000833167813679,-0.000833245942719)
Metadata:
 Band_1=Band 1
Image Structure Metadata:
 INTERLEAVE=BAND
Corner Coordinates:
Upper Left ( 100.9711740,  3.9502191) (100d58'16.23"E, 3d57' 0.79"N)
Lower Left ( 100.9711740,  2.0920806) (100d58'16.23"E, 2d 5'31.49"N)
Upper Right ( 103.0415960,  3.9502191) (103d 2'29.75"E, 3d57' 0.79"N)
Lower Right ( 103.0415960,  2.0920806) (103d 2'29.75"E, 2d 5'31.49"N)
Center   ( 102.0063850,  3.0211498) (102d 0'22.99"E, 3d 1'16.14"N)
Band 1 Block=2485x1 Type=Float32, ColorInterp=Undefined
 NoData Value=0
```
And corresponding .vrt file for incidenceAngle:
```
$ gdalinfo 20150328_20150304.vrt
Driver: VRT/Virtual Raster
Files: 20150328_20150304.vrt
    20150328_20150304
Size is 3615, 5244
Coordinate System is:
GEOGCRS["unknown",
  DATUM["unnamed",
    ELLIPSOID["Spheroid",6378137,298.257223563,
      LENGTHUNIT["metre",1,
        ID["EPSG",9001]]]],
  PRIMEM["Greenwich",0,
    ANGLEUNIT["degree",0.0174532925199433,
      ID["EPSG",9122]]],
  CS[ellipsoidal,2],
    AXIS["latitude",north,
      ORDER[1],
      ANGLEUNIT["degree",0.0174532925199433,
        ID["EPSG",9122]]],
    AXIS["longitude",east,
      ORDER[2],
      ANGLEUNIT["degree",0.0174532925199433,
        ID["EPSG",9122]]]]
Data axis to CRS axis mapping: 2,1
Origin = (100.741268439918002,5.442997285904920)
Pixel Size = (0.000833167813679,-0.000833245942719)
Image Structure Metadata:
 INTERLEAVE=BAND
Corner Coordinates:
Upper Left ( 100.7412684,  5.4429973) (100d44'28.57"E, 5d26'34.79"N)
Lower Left ( 100.7412684,  1.0734556) (100d44'28.57"E, 1d 4'24.44"N)
Upper Right ( 103.7531701,  5.4429973) (103d45'11.41"E, 5d26'34.79"N)
Lower Right ( 103.7531701,  1.0734556) (103d45'11.41"E, 1d 4'24.44"N)
Center   ( 102.2472193,  3.2582264) (102d14'49.99"E, 3d15'29.62"N)
Band 1 Block=128x128 Type=Float32, ColorInterp=Undefined
 NoData Value=0
```

I then get an error running prep_aria.py of MintPy when it tries to read the raster with GDAL since the sizes are mismatched (https://github.com/insarlab/MintPy/blob/master/mintpy/prep_aria.py#L311-L314). Here is the prep_aria.py traceback:
```
Traceback (most recent call last):
 File "/root/MintPy/mintpy/prep_aria.py", line 495, in <module>
  main()
 File "/root/MintPy/mintpy/prep_aria.py", line 483, in main
  write_geometry(inps.outfile[1],
 File "/root/MintPy/mintpy/prep_aria.py", line 313, in write_geometry
  data[data == ds.GetRasterBand(1).GetNoDataValue()] = np.nan
TypeError: 'NoneType' object does not support item assignment
```

To double check, I reprocessed using the latest commit of ARIA Tools (https://github.com/aria-tools/ARIA-tools/commit/cc947e3697f5b016aa15aa3f14d5a71196c97207) on another area of interest which had no interpolator/ rounding issues before. The older outputs had matching sizes with the .vrt, while the reprocessed outputs now have mismatched sizes like for this Kuala Lumpur case.

I do not know if this is by any chance related to any recent commits? Thanks again!

**Comment by sssangha** [comment]
@cheryltwj yes, I realized in the last commit I had forgotten to make sure the VRT files were updated after the extracted rasters were extracted/interpolated.

This is now addressed in my latest PR #166, so please try that.

**Comment by cheryltwj** [comment]
@sssangha Thanks for the fix! It works ok, this time I've ran ARIA Tools and MintPy from start to end without error.

**Comment by dbekaert** [comment]
Thanks @sssangha and @cheryltwj for looking into this
