### ISSUE TITLE
Vector files of product bounding box are not true shapefiles

### ISSUE THREAD

**Issue by EJFielding** [aria-tools/ARIA-tools#180]
**Describe the bug**
I opened two of the productBoundingBox “.shp” files extracted by `ariaExtract.py`, and QGIS says it is not a Shapefile but GeoJSON. 

**To Reproduce**
1. Download 
2. ariaExtract.py -f products/S1-GUNW-A-R-107-tops-20200625_20200619-003043-16794N_15045N-RR-35f2-v2_0_3.nc
```
...
No layers specified; only creating bounding box shapes
...

more productBoundingBox/productBoundingBox.shp
{
"type": "FeatureCollection",
"features": [
{ "type": "Feature", "properties": { "id": 0 }, "geometry": { "type": "Polygon", "coordinates": [ [ [ -95.491732437619106, 15.254601613767001 ], [ -95.480139655400805, 15.1973812782688 ], [ -96.265841421803799, 15.0460459810385 ], [ -96.545106536523704, 16.3983208386847 ], [ -95.753940481721898, 16.548823481423899 ], [ -95.732015688845493, 16.440605800758799 ], [ -94.943039871313502, 16.587647454937201 ], [ -94.954684574684705, 16.646262857948599 ], [ -94.218627064678302, 16.780453565178298 ], [ -93.9876553944611, 15.595759226299799 ], [ -94.697709773140502, 15.464431413739799 ], [ -94.6862330971082, 15.4066330126039 ], [ -95.491732437619106, 15.254601613767001 ] ] ] } }
]
}
```
**Expected behavior**
The `productBoundingBox/productBoundingBox.shp` is a GeoJSON file not an ESRI shapefile. It can be read by GDAL or QGIS because they recognize a GeoJSON file, but other software fails to read it correctly. The expected format for a Shapefile has these components:
20200625_20200619-bounds.dbf
20200625_20200619-bounds.prj
20200625_20200619-bounds.shp
20200625_20200619-bounds.shx

**Desktop (please complete the following information):**
 - ARIA-tools git tag: [e.g. git show --summary]
commit 561950cd7cea5013c226d8fd027213a860f95bce (HEAD -> dev, origin/dev, origin/HEAD)
Author: sssangha <sssangha@ucla.edu>
Date:   Mon Jun 15 19:32:28 2020 -0700

 - OS
MacOS

**Additional context**
It seems like it would be better to use the `.json` extension for the `productBoundingBox/productBoundingBox` files as this is more accurate.

**Comment by bbuzzanga** [comment]
I have also been tricked up by the extension and agree it should be `.json.` @sssangha  do you have a particular reason for adopting the `.shp`?

@EJFielding could you let us know what software failed to read the `productBoundingBox` files correctly? My QGIS v3.10.4 imports them correctly as is.

**Comment by EJFielding** [comment]
I was working on uploading the specially processed ARIA standard coseismic products for the June 2020 Oaxaca earthquake to the Harvard Dataverse [repository.](https://dataverse.harvard.edu/) It used the file extension and got confused.

**Comment by EJFielding** [comment]
I don't know if anybody has tried the ESRI ArcGIS software. I suspect it may be more strict.

**Comment by dbekaert** [comment]
We should make it technically correct and just change `.shp` to `.json`; and update the code to load `.json` 

Optionally, we could either provide documentation or also generate at the same time the shape-file for it, the latter will cause clutter and 6 files per product to be generated. Personally given its a one-liner for gdal, we put it in documentation. 
```ogr2ogr -f "ESRI Shapefile" destination_data.shp "source-data.json"```

**Comment by EJFielding** [comment]
Yes, changing the file name to `.json` would be great. Adding that one-liner for GDAL to convert to true ESRI Shapefile format makes perfect sense.

**Comment by sssangha** [comment]
@EJFielding I too was unable to emulate this issue. I'm able to load the shapefile just fine in QGIS 3.10.6.
<img width="698" alt="Screen Shot 2020-07-01 at 12 04 28 PM" src="https://user-images.githubusercontent.com/13227405/86281921-24310380-bb93-11ea-8ce7-f5a9aa1d26fa.png">

**Comment by sssangha** [comment]
Am working on an update now. Will push shortly

**Comment by EJFielding** [comment]
> @EJFielding I too was unable to emulate this issue. I'm able to load the shapefile just fine in QGIS 3.10.6.
> <img alt="Screen Shot 2020-07-01 at 12 04 28 PM" width="698" src="https://user-images.githubusercontent.com/13227405/86281921-24310380-bb93-11ea-8ce7-f5a9aa1d26fa.png">

Yes, QGIS is very lenient and has no trouble. Other software is more strict.

**Comment by sssangha** [comment]
Ok I issued a PR to change all shapefile extensions to '.json'. As I said there, we will have to make sure to update the notebooks to be consistent with this convention and also add in the documentation concerning the one-liner conversion of the shapefile for the user's reference.

I agree adding in the shapefile with the json files through ARIA-tools will lead to too much clutter.
