### ISSUE TITLE
Add compatibility to GMT grid files

### ISSUE THREAD

**Issue by EJFielding** [aria-tools/ARIA-tools#185]
**Describe the bug**
Output files have unequal spacing and inconsistent geotransform information.

**To Reproduce**
1. Download 
`wget https://aria-share.jpl.nasa.gov/20200623_Oaxaca_Mexico_EQ/Displacements/S1-GUNW_COSEISMIC-A-R-107-tops-20200625_20200619-003043-16794N_15045N-RR-35f2-v2_0_3.nc`
2. Command used
```
ariaExtract.py -f "products/S1-GUNW-A-R-107-tops-20200625_20200619-003043-16794N_15045N-RR-35f2-v2_0_3.nc" -l all -d download -w products -m download --outputFormat ENVI
gdal_calc.py -A products/unwrappedPhase/20200625_20200619.vrt -B products/connectedComponents/20200625_20200619.vrt --outfile results/S1_A107_20200625_20200619_disp_cm.tif --calc='((A*(B>0))/(4*pi)*5.546576)' --format=GTiff --NoDataValue=0 --overwrite
gdal_translate -of GMT S1_A107_20200625_20200619_disp_cm.tif S1_A107_20200625_20200619_disp_cm.grd
gmt grdlandmask -Glandmask.grd -RS1_A107_20200625_20200619_disp_cm.grd
gmt grdinfo landmask.grd
```
3. Error Output
```
grdinfo [ERROR]: (x_max-x_min) must equal (NX + eps) * x_inc), where NX is an integer and |eps| <= 0.0001.
grdinfo (gmtlib_read_grd_info): Use grdedit -A on your grid file to make region and increments compatible [landmask.grd]
landmask.grd: Title: z
landmask.grd: Command: grdlandmask -Glandmask.grd -RS1_A107_20200625_20200619_disp_cm.grd
landmask.grd: Remark: Derived from the low resolution shorelines
landmask.grd: Pixel node registration used [Geographic grid]
landmask.grd: Grid file format: nf = GMT netCDF format (32-bit float), CF-1.7
landmask.grd: x_min: -96.5451065365 x_max: -93.9876553945 x_inc: 0.00083331741351 (3 sec) name: longitude n_columns: 3069
landmask.grd: y_min: 15.046045981 y_max: 16.7804535652 y_inc: 0.000833449103383 name: latitude n_rows: 2081
landmask.grd: z_min: 0 z_max: 1 name: z
landmask.grd: scale_factor: 1 add_offset: 0
landmask.grd: format: netCDF-4 chunk_size: 134,131 shuffle: on deflation_level: 3
```
**Expected behavior**
There should be a way to get the output into a correct GMT grid for further processing. The output file has been resampled from the original 3-arcsecond spacing to have different "x_inc" and "y_inc" values. In addition the "xmin" and "xmax" that don't exactly fit the "xinc" times the number of columns. This makes it an invalid GMT grid that can't be used for other calculations.

**Screenshots**

**Desktop (please complete the following information):**
 - ARIA-tools git tag: [e.g. git show --summary]
commit f39a8ee74acf8c40e641560a2d2ef2eb220acdb4 (HEAD -> dev, origin/dev, origin/HEAD)
Merge: 561950c 95dc360
Author: sssangha <sssangha@ucla.edu>
Date:   Fri Jun 19 18:15:38 2020 -0700

    Merge pull request #176 from sssangha/sss_avgrasterfix

    Fixed bug in average raster generation and reporting failed IFGs

 - OS
MacOS 10.14.6

**Additional context**
I need to use GMT grdmath to do additional calculations but it can't use the files.

**Comment by ehavazli** [comment]
hello @EJFielding,

I wasn't able to reproduce your error because (I think) there are some inconsistencies in the file names you gave in your commands. Also I have GMT6 but the grdlandmask throws the error due to -R not being a valid format:
```
grdlandmask [ERROR]: Could not parse S1_A107_20200625_20200619_disp_cm.grd into Geographical, Cartesian, or Temporal coordinates!grdlandmask [ERROR]: Syntax error -R option. Correct syntax:
	-R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]
	  Append r if giving lower left and upper right coordinates
	-Rg or -Rd for global domain
	-R<grdfile> to take the domain from a grid file
grdlandmask [ERROR]: Offending option -RS1_A107_20200625_20200619_disp_cm.grd

```

However, I think you can define the final product output format as GSBG in gdal which is the grd format I successfully use with gdal and GMT. I am leaving the command below.

```
gdal_calc.py -A products/unwrappedPhase/20200625_20200619.vrt -B products/connectedComponents/20200625_20200619.vrt --outfile results/S1_A107_20200625_20200619_disp_cm.tif --calc='((A*(B>0))/(4*pi)*5.546576)' --format=GSBG --NoDataValue=0 --overwrite
```

**Comment by EJFielding** [comment]
I have not heard of GSBG format before.

**Comment by ehavazli** [comment]
Golden Software Binary Grid

https://gdal.org/drivers/raster/gsbg.html

**Comment by EJFielding** [comment]
Thanks.

It is also possible to extract the full-resolution layers directly from the original ARIA NetCDF files with:
```
gmt grdconvert 'S1-GUNW_COSEISMIC-A-R-107-tops-20200625_20200619-003043-16794N_15045N-RR-35f2-v2_0_3.nc=gd?NETCDF:"S1-GUNW_COSEISMIC-A-R-107-tops-20200625_20200619-003043-16794N_15045N-RR-35f2-v2_0_3.nc":/science/grids/data/amplitude' -Gamp.grd
```
This keeps the original exact 3-arcsecond spacing.

**Comment by EJFielding** [comment]
Here is the info about the GMT grid created directly with grdconvert:
```
grdinfo amp.grd
amp.grd: Title: Produced by grdconvert
amp.grd: Command: grdconvert S1-GUNW_COSEISMIC-A-R-107-tops-20200625_20200619-003043-16794N_15045N-RR-35f2-v2_0_3.nc=gd?NETCDF:"S1-GUNW_COSEISMIC-A-R-107-tops-20200625_20200619-003043-16794N_15045N-RR-35f2-v2_0_3.nc":/science/grids/data/amplitude -Gamp.grd
amp.grd: Remark:
amp.grd: Gridline node registration used
amp.grd: Grid file format: nf (# 18) GMT netCDF format (float)  (COARDS-compliant) [DEFAULT]
amp.grd: x_min: -96.5533333333 x_max: -93.91 x_inc: 0.000833333333333 name: x nx: 3173
amp.grd: y_min: 15.045 y_max: 16.795 y_inc: 0.000833333333333 name: y ny: 2101
amp.grd: z_min: 0 z_max: 754838.0625 name: z
amp.grd: scale_factor: 1 add_offset: 0
```
It has the original 3-arcsecond spacing and spatial extent of the ARIA product. Somewhere in `ariaExtract.py` the full-resolution layers are resampled and get inconsistent extent and spacing.

**Comment by dbekaert** [comment]
@EJFielding @ehavazli  Would be happy to welcome an example notebook on how to make a GMT6 figure:

e.g. how to plot up an unwrapped IFG in cm units in GMT with a color figure and scalebar.
e.g. how to plot up a wrapped IFG in rad with a colorbar and scale bar

The Hawaii IFG we use for the extract notebook would be well suitable example.
it already captures how to download the product, how to stitch it, and would then we great to see how it gets plotted.

**Comment by EJFielding** [comment]
@dbekaert I can help with a notebook on GMT plotting. We still need to fix the `ariaExtract.py` output. Did you mean using the `gmt grdconvert` command to make GMT files directly and then plotting those? When I use `gmt grdconvert` on the GUNW_COSEISMIC pair, I get a grid that is 3173 by 2101, but the `ariaExtract` output is 3069 by 2081, so the size changes somewhat. That means that I can't use the LOS vector files from `ariaExtract` with the unwrapped phase from `grdconvert` without doing some additional resampling.

**Comment by sssangha** [comment]
@EJFielding it would be best to use the outputs of ```ariaExtract.py``` directly and plot through GMT, making sure to specify the GSBG format with the ```-of``` argument as Emre suggested so you can directly leverage the outputs of ```ariaExtract.py```. Makes sense?

**Comment by EJFielding** [comment]
@sssangha Yes, the GSBG format helps avoid an extra step of running `gdal_translate` to make a file that GMT can read, but it does not fix the problem that the pixel spacings and image limits are not quite correct, so GMT refuses to work with the files from `ariaExtract.py`.

**Comment by EJFielding** [comment]
I tried using the -of GSBG in the `ariaExtract.py` and now I am getting errors:
```
***Extract Product Function:***
All (1) GUNW products meet spatial bbox criteria.
Group GUNW products into spatiotemporally continuous interferograms.
All (1) interferograms are spatially continuous.
All layers are to be extracted, pass all keys.
Thread count specified for gdal multiprocessing = 2
***Downloading water mask... ***
Downloaded 3 arc-sec SRTM DEM here: products/DEM/SRTM_3arcsec.dem
Generating: unwrappedPhase - [==================================================] 20200625_20200619
Generating: coherence - [==================================================] 20200625_20200619
Generating: connectedComponents - [==================================================] 20200625_20200619
Generating: amplitude - [==================================================] 20200625_20200619/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/site-packages/ARIAtools/extractProduct.py:344: RuntimeWarning: overflow encountered in multiply
  update_file.GetRasterBand(1).WriteArray(mask.ReadAsArray()*gdal.Open(outname+'.vrt').ReadAsArray())

Generating: bPerpendicular - [==================================================] 20200625_20200619/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/site-packages/ARIAtools/extractProduct.py:633: RuntimeWarning: overflow encountered in multiply
  out_interpolated = mask.ReadAsArray()*out_interpolated

Generating: bParallel - [==================================================] 20200625_20200619
Generating: incidenceAngle - [==================================================] 20200625_20200619
Generating: lookAngle - [==================================================] 20200625_20200619
Generating: azimuthAngle - [==================================================] 20200625_20200619
```
I verified that it works with `ariaExtract.py -f "products/S1-GUNW_COSEISMIC-A-R-107-tops-20200625_20200619-003043-16794N_15045N-RR-35f2-v2_0_3.nc" -l all -d download -w products -m download --outputFormat ENVI`, which is the default, but with `ariaExtract.py -f "products/S1-GUNW_COSEISMIC-A-R-107-tops-20200625_20200619-003043-16794N_15045N-RR-35f2-v2_0_3.nc" -l all -d download -w GSBG -m download --outputFormat GSBG` I get those errors shown above.

**Comment by sssangha** [comment]
@EJFielding I was unable to duplicate this error:
```
(ARIA-tools) [ssangha@leffe Eric_test]$ ariaExtract.py -f "products/S1-GUNW_COSEISMIC-A-R-107-tops-20200625_20200619-003043-16794N_15045N-RR-35f2-v2_0_3.nc" -l all -d download -w test_dir --outputFormat GSBG
***Extract Product Function:***
All (1) GUNW products meet spatial bbox criteria.
Group GUNW products into spatiotemporally continuous interferograms.
All (1) interferograms are spatially continuous.
All layers are to be extracted, pass all keys.
Thread count specified for gdal multiprocessing = 2
Downloaded 3 arc-sec SRTM DEM here: test_dir/DEM/SRTM_3arcsec.dem
Generating: unwrappedPhase - [==================================================] 20200625_20200619 
Generating: coherence - [==================================================] 20200625_20200619 
Generating: connectedComponents - [==================================================] 20200625_20200619 
Generating: amplitude - [==================================================] 20200625_20200619 
Generating: bPerpendicular - [==================================================] 20200625_20200619 
Generating: bParallel - [==================================================] 20200625_20200619 
Generating: incidenceAngle - [==================================================] 20200625_20200619 
Generating: lookAngle - [==================================================] 20200625_20200619 
Generating: azimuthAngle - [==================================================] 20200625_20200619 
```

We did push a series of commits, some of which addressed minor issues with the metadata fields, so could you please try to update to the latest release and relaunch? Thanks!

**Comment by EJFielding** [comment]
@sssangha I did an update last night and ran it again with the same result. It seems to be a problem with the masking. I notice that you did not include the masking flag. This is what I used `ariaExtract.py -f "products/S1-GUNW_COSEISMIC-A-R-107-tops-20200625_20200619-003043-16794N_15045N-RR-35f2-v2_0_3.nc" -l all -d download -w GSBG -m download --outputFormat GSBG`
The same command with the output format set to `ENVI` works fine, so it is some kind of bug when the GSBG output is used.
Here is the output from running first the ENVI version and then the GSBG version both with the masking turned on.
```
***Extract Product Function:***
All (1) GUNW products meet spatial bbox criteria.
Group GUNW products into spatiotemporally continuous interferograms.
All (1) interferograms are spatially continuous.
All layers are to be extracted, pass all keys.
Thread count specified for gdal multiprocessing = 2
***Downloading water mask... ***
Downloaded 3 arc-sec SRTM DEM here: products/DEM/SRTM_3arcsec.dem
Generating: unwrappedPhase - [==================================================] 20200625_20200619
Generating: coherence - [==================================================] 20200625_20200619
Generating: connectedComponents - [==================================================] 20200625_20200619
Generating: amplitude - [==================================================] 20200625_20200619
Generating: bPerpendicular - [==================================================] 20200625_20200619
Generating: bParallel - [==================================================] 20200625_20200619
Generating: incidenceAngle - [==================================================] 20200625_20200619
Generating: lookAngle - [==================================================] 20200625_20200619
Generating: azimuthAngle - [==================================================] 20200625_20200619
***Extract Product Function:***
All (1) GUNW products meet spatial bbox criteria.
Group GUNW products into spatiotemporally continuous interferograms.
All (1) interferograms are spatially continuous.
All layers are to be extracted, pass all keys.
Thread count specified for gdal multiprocessing = 2
***Downloading water mask... ***
Downloaded 3 arc-sec SRTM DEM here: GSBG/DEM/SRTM_3arcsec.dem
Generating: unwrappedPhase - [==================================================] 20200625_20200619/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/site-packages/ARIAtools/unwrapStitching.py:279: RuntimeWarning: overflow encountered in multiply
  update_file=update_file.GetRasterBand(1).WriteArray(self.mask.ReadAsArray()*gdal.Open(self.outFileUnw+'.vrt').ReadAsArray())

Generating: coherence - [==================================================] 20200625_20200619
Generating: connectedComponents - [==================================================] 20200625_20200619
Generating: amplitude - [==================================================] 20200625_20200619/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/site-packages/ARIAtools/extractProduct.py:344: RuntimeWarning: overflow encountered in multiply
  update_file.GetRasterBand(1).WriteArray(mask.ReadAsArray()*gdal.Open(outname+'.vrt').ReadAsArray())

Generating: bPerpendicular - [==================================================] 20200625_20200619/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/site-packages/ARIAtools/extractProduct.py:647: RuntimeWarning: overflow encountered in multiply
  out_interpolated = mask.ReadAsArray()*out_interpolated

Generating: bParallel - [==================================================] 20200625_20200619
Generating: incidenceAngle - [==================================================] 20200625_20200619
Generating: lookAngle - [==================================================] 20200625_20200619
Generating: azimuthAngle - [==================================================] 20200625_20200619
```
The unwrapped phase PNG preview files generated by `ariaExtract` confirm that the ENVI output is good.
![20200625_20200619](https://user-images.githubusercontent.com/7253576/87192269-fa6e8f80-c2aa-11ea-8348-25d1c03fed0d.png)
But the GSBG output is bad.
![20200625_20200619](https://user-images.githubusercontent.com/7253576/87192325-1a9e4e80-c2ab-11ea-801d-a9f421c54fdd.png)

**Comment by sssangha** [comment]
@EJFielding very strange, looks like a numpy issue. The PNG previews indeed look bad, but the phase fields in the actual rasters are fine. But the problems seems to be that with the GSBG format, for some reason the masked areas are inconsistently set to infinity (see navy blue values in the attached image), which is what is raising this warning. I can come up with a bandage solution to simply replace infs with 0s, but I will work to see if I can come up with a cleaner permanent solution:
<img width="909" alt="Screen Shot 2020-07-10 at 1 13 34 PM" src="https://user-images.githubusercontent.com/13227405/87198147-7f5ba800-c2af-11ea-8907-a9e48cdaee0a.png">

**Comment by EJFielding** [comment]
@sssangha Yes, you are right. In fact, there are areas of positive and negative infinity in the ocean, which gives that strange pattern with autoscaling.

**Comment by sssangha** [comment]
@EJFielding thanks for helping me hash out what I wouldn't necessarily call a bug per se, but an oversight. 

It seems for some data formats the nodata value for the mask file is set to Inf/-Inf. I now make sure to always define the nodata value as 0 for maskfiles. Please test out the PR I just posted.

**Comment by dbekaert** [comment]
@sssangha Can you confirm that the extract product do no longer have the default standard product sampling?
If that is the case it would mean that the DEM does not have the -tap command in its gdal warp.
The DEM as we download should have regular spacing.

if that is fixed gdal translate and GMT should be compatible also for values extracted from aira-tools.

**Comment by ehavazli** [comment]
@sssangha @dbekaert 
to cut some of the backtracking work,
here is the pixel size from the product:

```
Pixel Size = (0.000833333333333,-0.000833333333333)
```
here is the geotransform value from the unwrappePhase vrt file

```
 (0.00083331741351013496, -0.00083344910338289198)
```

please check the code starting from line 593 to line 603 in extractProduct.py:

https://github.com/aria-tools/ARIA-tools/blob/7d173b0aa2b4a3a6459ac674f253c7e4058b803f/tools/ARIAtools/extractProduct.py#L593:L603

**Comment by dbekaert** [comment]
when tap is enforced it cannot be used together with width and length. @sssangha suggest to potentially reverse engineer the with and length to be integer multiples of the original posting.

**Comment by dbekaert** [comment]
@ehavazli can you confirm that the sampling is now identically?  see PR #192

**Comment by ehavazli** [comment]
@dbekaert @EJFielding @sssangha 

#192 solved the problem in my environment.

**Comment by dbekaert** [comment]
@ehavazli could you show some figures of the results here?
Just to clarify the error is gone, but did you also have a workaroudn for the +- inf

**Comment by dbekaert** [comment]
@EJFielding The files should not be compatible in terms of grid-sampling. Thanks @sssangha for implementing. This should at least allow not to use ARIA-extract to anotehr format when loading into GMT.

**Comment by EJFielding** [comment]
The new version now works great! I was able to set the output format to `ENVI` and get a file that I can successfully convert to GMT with `gdal_translate`. I had to do one extra `grdmath` step to set the zero pixels to `NaN`, but it did not complain about the grid spacing and extent. Then I was able to load into the Python fault modeling software that I use (Classic Source Inversion). Here is the output from the matplotlib call in that software.
![new-covar-input_check](https://user-images.githubusercontent.com/7253576/87742313-4cc41a80-c79b-11ea-90a0-a3948f78bfe4.png)
Thanks @sssangha !

This is the command that I used:
```
ariaExtract.py -f "products/S1-GUNW_COSEISMIC-A-R-107-tops-20200625_20200619-003043-16794N_15045N-RR-35f2-v2_0_3.nc" -l all -d download -w ENVI -m download --outputFormat ENVI
gdal_calc.py -A ENVI/unwrappedPhase/20200625_20200619.vrt -B ENVI/connectedComponents/20200625_20200619.vrt --outfile ENVI/results/S1_A107_20200625_20200619_disp_cm.tif --calc='((A*(B>0))/(4*pi)*5.546576)' --format=GTiff --NoDataValue=0 --overwrite
gdal_translate S1_A107_20200625_20200619_disp_cm.tif S1_A107_20200625_20200619_disp_cm.grd -of GMT
```

**Comment by dbekaert** [comment]
That great @EJFielding

**Comment by EJFielding** [comment]
One other comment while I still have a browser tab open about GSBG (https://desktop.arcgis.com/en/arcmap/latest/manage-data/raster-and-images/supported-raster-dataset-file-formats.htm). It seems that the standard file extension for GSBG files is `.grd` and other formats have standard extensions. This is usually not a problem on MacOS or Linux, but people trying to use Windows might have problems if the ARIA-tools output files don't have the standard extension. I add this comment in case it helps someone later.
