### ISSUE TITLE
remove x-display dependency 

### ISSUE THREAD

**Issue by rzinke** [aria-tools/ARIA-tools#189]
**Describe the bug**
I downloaded new data processed on the HEC (v 2.0.3) and attempted to run the ariaTSsetup.py routines using those data. Instead, the routine ends after the incidence angle step with an error message. This might be a backend issue for the graphics(?).

**To Reproduce**
1. ariaDownload.py -t 41 --start 20150101 --end 20170101
2. ariaTSsetup.py -f "products/*.nc" -w ML3 -d download -m download -nt 8 -ml 3 -v
3. I get the following error message:
15 out of 92 interferograms rejected for not meeting specified spatial thresholds
Download/cropping DEM
Downloaded 3 arc-sec SRTM DEM here: ML3/DEM/SRTM_3arcsec.dem
***Downloading water mask... ***
Extracting unwrapped phase, coherence, and connected components for each interferogram pair
Generating: unwrappedPhase - [==================================================] 20170101_20161208 3595s /   111s
Generating: coherence - [==================================================] 20170101_20161208 2070s /    64s

Extracting single incidence angle, look angle and azimuth angle files valid over common interferometric grid
Generating: incidenceAngle - [==================================================] 20150512_20150301qt.qpa.xcb: could not connect to display localhost:10.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, webgl, xcb.

Aborted (core dumped)
(ARIA-tools) [rzinke@sar HECtest]$ rm Point*.pdf/u/sar-r0/rzinke/python/miniconda3/envs/ARIA-tools/lib/python3.6/site-packages/joblib/externals/loky/backend/resource_tracker.py:266: UserWarning: resource_tracker: There appear to be 6 leaked semlock objects to clean up at shutdown
  (len(rtype_cache), rtype))

**Desktop (please complete the following information):**
 - commit 7d173b0aa2b4a3a6459ac674f253c7e4058b803f (HEAD -> dev, aria-tools/dev)
Author: rzinke <48299159+rzinke@users.noreply.github.com>
Date:   Thu Jul 9 18:17:29 2020 -0700
    Automatically exclude incomplete dates ariaAOIassist (#184)
    * Expanded default latitude bounds to +- 90
    * Fixed shebang expression for ariaAOIassist.py
    * Changed default lat bounds to +- 75
    * Changed class init lat bounds to +- 75
    * Automatically exclude incomplete dates ariaAOIassist.py
    * Removed assertation
 - OS Linux SAR machine at JPL

**Comment by EJFielding** [comment]
@rzinke I see `could not connect to display localhost:10.0` in the output. If you are running this from a shell that was disconnected with `screen`, it might have lost permission to connect to the X display. I am not sure what `ariaTSsetup.py` is doing with an X display connection, but it might be automatic when `matplotlib` is called. It does seem like there should be a way to tell `matplotlib` to generate output files without connecting to the display.

**Comment by dbekaert** [comment]
@rzinke, @EJFielding is right. This has probably to do with a figure being saved. If ran in a sceen it fails. Agreed with @EJFielding that option to not require a display would be better. We have that also implemented for the other routines, so i suspect this is a new one that got added when correcting for baseline features @sssangha ?

**Comment by dbekaert** [comment]
@rzinke, without running in screen this works fine, so not considering this a bug and have updated the title accordingly.

To get it to work for display,  you will need to modify this: https://github.com/aria-tools/ARIA-tools/blob/7d173b0aa2b4a3a6459ac674f253c7e4058b803f/tools/ARIAtools/extractProduct.py#L460-L477 

See here for information:  https://stackoverflow.com/questions/4931376/generating-matplotlib-graphs-without-a-running-x-server
In addition,  you can see here for how it was done for ariaPlot.py in the past.

**Comment by rzinke** [comment]
Confirmed. Many thanks, @EJFielding and @dbekaert.

**Comment by dbekaert** [comment]
@rzinke could you issue a PR with the change?

**Comment by dbekaert** [comment]
Closing this as its outdated
