### ISSUE TITLE
[WANTED FEATURE] Reporting of unwrapped phase stitching success

### ISSUE THREAD

**Issue by EJFielding** [aria-tools/ARIA-tools#193]
**Is your feature request related to a problem? Please describe.**

I am trying to construct an InSAR time series across the Himalayas from the ARIA standard products on track 19, and some pairs have low coherence in the high peaks region. Some of the stitched scenes from `ariaTSsetup.py` have large unwrapping errors along the stitching boundary. See this image of the stitched unwrapped phase products from MintPy:
![unwrapPhase](https://user-images.githubusercontent.com/7253576/87723460-b1b54b80-c76e-11ea-8ce6-8d5fe2549447.png)

**Describe the solution you'd like**

It would be helpful if the stitching code reported the amount of misfit in the overlap between scenes when it is doing the stitching.

**Describe alternatives you've considered**

I can try to use the MintPy tools to fix unwrapping errors with the misclosure estimates, but it would be helpful to know which pairs are very bad and potentially remove those before attempting to fix the errors.

**Additional context**
Here is an image from MintPy of the connected components masks.
![connectComponent](https://user-images.githubusercontent.com/7253576/87723719-11abf200-c76f-11ea-8827-0dedcba1743a.png)
These are the commands to download and setup the data:
```
ariaDownload.py --bbox "26 29 83 86" --track 19 -o download
# need bigger overlap threshold for bigger area
ariaTSsetup.py -f 'products/*.nc' --bbox "26 29 83 86" -d download --mask download -w bbox26_29_ml3 -mo 60000 -ml 3 -v
```
At the moment, many of the available pairs on this track have long time intervals. Later, I would like to be able to exclude the pairs that are likely to be problematic.

**Comment by dbekaert** [comment]
@EJFielding  Perhaps a better approach would be to expand and avoid minimization/ stitching on a single unwrapping connected component. Feel free to play with the two stage unwrapping on the `2stage` branch. At this point its not mature enough to be the default stitching method. Also note that Mintpy can still leverage the products with stitching artifacts by enabling some of the addition unwrapping correction methods included. Feel free to make changes and issue a PR on the beta feature.

**Comment by EJFielding** [comment]
@dbekaert Looking again at the connected components masks, I see that the unwrapping errors are in areas of the Himalayas with no connected components because of the low coherence. I don't know much about how the two-stage unwrapper works, but I assume that it ignores the areas outside the connected components. There is a good connected component on the east side on each pair across the frame boundary, so it is stitching based on that. The area to the west is simply unreliable phase. I think I need to apply a connected components mask to the data before or during the MintPy analysis. It still would be helpful to provide a warning for unsophisticated users that not all of the stitching is reliable.

**Comment by mgovorcin** [comment]
I am going to close this issue ticket as we have updated unwrapper stitcher method [PR: 368](https://github.com/aria-tools/ARIA-tools/pull/368)
