### ISSUE TITLE
[BUG] meta-data verification 

### ISSUE THREAD

**Issue by rzinke** [aria-tools/ARIA-tools#194]
**Describe the bug**
Not quite sure where to start with this error message. I am running ariaTSsetup.py on the new Tibet track 41 data. Lately, I moved all the old v 2.0.2 data to a separate folder and downloaded all the new, v 2.0.3 data to the folder Track041/AllProducts. When I run TSsetup, I now get an error message in the finalize_metadata section (see below).

**To Reproduce**
1. Download 
ariaDownload.py -t 41 -w Track041/AllProducts
2. Command used
ariaTSsetup.py -f '/u/sar-r2/rzinke/Tibet/Track041/AllProducts/*.nc' -w ML3v3 -d download -m download -nt 8 -ml 3
3. Error Output
Traceback (most recent call last):
  File "/u/sar-r0/rzinke/python/miniconda3/envs/ARIA-tools/bin/ariaTSsetup.py", line 15, in <module>
    main(inps)
  File "/u/sar-r0/rzinke/python/miniconda3/envs/ARIA-tools/lib/python3.6/site-packages/ARIAtools/tsSetup.py", line 275, in main
    export_products([dict(zip([k for k in set(k for d in standardproduct_info.products[1] for k in d)], [[item for sublist in [list(set(d[k])) for d in standardproduct_info.products[1] if k in d] for item in sublist] for k in set(k for d in standardproduct_info.products[1] for k in d)]))], standardproduct_info.bbox_file, prods_TOTbbox, layers, dem=demfile, lat=Latitude, lon=Longitude, mask=inps.mask, outDir=inps.workdir, outputFormat=inps.outputFormat, stitchMethodType='overlap', verbose=inps.verbose, num_threads=inps.num_threads, multilooking=inps.multilooking)
  File "/u/sar-r0/rzinke/python/miniconda3/envs/ARIA-tools/lib/python3.6/site-packages/ARIAtools/extractProduct.py", line 343, in export_products
    finalize_metadata(outname, bounds, dem_bounds, prods_TOTbbox, dem, lat, lon, mask, outputFormat, verbose=verbose)
  File "/u/sar-r0/rzinke/python/miniconda3/envs/ARIA-tools/lib/python3.6/site-packages/ARIAtools/extractProduct.py", line 615, in finalize_metadata
    data_array = metadata_qualitycheck(data_array, os.path.basename(os.path.dirname(outname)), outname, verbose).data_array
  File "/u/sar-r0/rzinke/python/miniconda3/envs/ARIA-tools/lib/python3.6/site-packages/ARIAtools/extractProduct.py", line 412, in __init__
    self.__run__()
  File "/u/sar-r0/rzinke/python/miniconda3/envs/ARIA-tools/lib/python3.6/site-packages/ARIAtools/extractProduct.py", line 505, in __run__
    rsquaredarr_rng, std_errarr_rng = self.__getCovar__('range')
  File "/u/sar-r0/rzinke/python/miniconda3/envs/ARIA-tools/lib/python3.6/site-packages/ARIAtools/extractProduct.py", line 476, in __getCovar__
    if (min(rsquaredarr) < 0.9 and max(std_errarr) > 0.01) or (i[0]==(len(eval('self.data_array_band%s'%(arrT)))-1)):
ValueError: min() arg is an empty sequence

**Expected behavior**
I am familiar with track 41, and the acquisition scheme is simple, so usually these processes go without a hitch.

**Desktop (please complete the following information):**
$ git show --summary
commit afbb8d96c6ead706f49932f0802e0d0ede6b6fea (HEAD -> dev, origin/dev, origin/HEAD)
Merge: 4b50e46 76ca2b0
Author: RobZinke <zink.oxide81@gmail.com>
Date:   Fri Jul 17 07:58:38 2020 -0700

    Merge branch 'dev' of https://github.com/aria-tools/ARIA-tools into dev
 - JPL sar server

**Comment by dbekaert** [comment]
This is new code that @sssangha added to verify some of the geometry meta-data and find any potential issues. So likely did not exit when you ran it in the past.

**Comment by EJFielding** [comment]
Probably the new code did not exist before, either ;-).

**Comment by sssangha** [comment]
@rzinke, this looks very similar to a bug @bbuzz31 encountered and outlined in #182. Specifically, a subroutine was designed to remove columns and rows with any masked value. So if an entire row were to be masked, then the entire raster would be masked! Now a careful check is implemented to appropriated truncate arrays of columns and rows made up exclusively of masked values. I hope somehow my fix did not get overwritten.

To help me debug, can you please re-run in verbose mode and perhaps add some print statements at the top of the loop so then I can see which layer/products are raising this issue? You are running on a large stack so it would be easier to debug if we can isolate and iterate on a specific product. Let me know if you would like some guidance on where and what print statements would be useful.

**Comment by rzinke** [comment]
Okay, thanks for the hints. I will get a subset of track41 and try to replicate the error to make sure that it is not dependent on a single product. Once I have done that, I will find the section of code that produces the error and put some flags near it to tell us which products are giving us trouble, and at what stage in the processing.

**Comment by rzinke** [comment]
Hi @sssangha, I am at line 476 in extractProduct.py (/u/sar-r0/rzinke/python/miniconda3/envs/ARIA-tools/lib/python3.6/site-packages/ARIAtools/extractProduct.py). Can you help me figure out what line to print there to display the product name, or some other information that would help you?

**Comment by sssangha** [comment]
@rzinke, I took a closer look at the version you are using and it looks like it had diverged from the dev. In particular, the relevant changes I made back under PR #181 were superceded. I confirm that the tests outlined in issue #182, which raised identical errors to what you see here, are circumvented with the dev branch.

Please update your workspace with the current dev version and let me know whether the issue persists. It looks like your changes to ```ariaAOIassist``` have already been incorporated too in the dev, but please confirm with me in case I overlooked something.

**Comment by rzinke** [comment]
Hi @sssangha, thanks for taking a look. 
That is very surprising to me because just yesterday I pulled from aria-tools/dev. I will pull again and git it a try... Stay tuned.

**Comment by rzinke** [comment]
Hi again, @sssangha. I pulled from aria-tools dev and reinstalled ARIA-tools with the setup.py build / install. I confirmed that the .../lib/python3.6/site-packages/ARIAtools/extractProduct.py file is identical to that on the dev page. I get the same error message. 

Anything I can do to help debug?

**Comment by sssangha** [comment]
@rzinke I am unable to replicate. Can you try to re-run ```ariaTSsetup.py``` in verbose mode? That will print the product name for each call.

But perhaps, just as a sanity check, can you first run some smaller derivative of the test Brett shared in issue #182 ?
It's a bit clunky, but just to download the bare minimum of products, try this:
```
ariaDownload.py -t 4 -o download -b '36.75 37.225 -76.655 -75.928' -i '20161205_20150825'
ariaDownload.py -t 4 -o download -b '36.75 37.225 -76.655 -75.928' -i '20161229_20150825'
ariaDownload.py -t 4 -o download -b '36.75 37.225 -76.655 -75.928' -i '20170122_20150310'

ariaTSsetup.py -f 'products/S1*.nc' -b '36.75 37.225 -76.655 -75.928' -w outputtest -d Download --bperp -nt 12 -of ISCE -v
```

**Comment by rzinke** [comment]
Hi @sssangha, I ran the scripts Brett used and they worked without a hitch ("stack generated").

I will rerun in verbose mode and try to isolate the problem.

**Comment by dbekaert** [comment]
@rzinke can this be  closed?

**Comment by rzinke** [comment]
Ah, not yet. Let me check on it. There might have been some corrupted files since I have not encountered this issue with any other data set.

**Comment by rzinke** [comment]
I am still getting the same error as above:

Generating: unwrappedPhase - [==================================================] 20200708_20200626 2935s /   468s
Generating: coherence - [==================================================] 20200708_20200626 9201s /   187s

Extracting single incidence angle, look angle and azimuth angle files valid over common interferometric grid
Generating: incidenceAngle - [==================================================] 20141207_20141113Traceback (most recent call last):
  File "/u/sar-r0/rzinke/python/miniconda3/envs/ARIA-tools/bin/ariaTSsetup.py", line 15, in <module>
    main(inps)
  File "/u/sar-r0/rzinke/python/miniconda3/envs/ARIA-tools/lib/python3.6/site-packages/ARIAtools/tsSetup.py", line 275, in main
    export_products([dict(zip([k for k in set(k for d in standardproduct_info.products[1] for k in d)], [[item for sublist in [list(set(d[k])) for d in standardproduct_info.products[1] if k in d] for item in sublist] for k in set(k for d in standardproduct_info.products[1] for k in d)]))], standardproduct_info.bbox_file, prods_TOTbbox, layers, dem=demfile, lat=Latitude, lon=Longitude, mask=inps.mask, outDir=inps.workdir, outputFormat=inps.outputFormat, stitchMethodType='overlap', verbose=inps.verbose, num_threads=inps.num_threads, multilooking=inps.multilooking)
  File "/u/sar-r0/rzinke/python/miniconda3/envs/ARIA-tools/lib/python3.6/site-packages/ARIAtools/extractProduct.py", line 343, in export_products
    finalize_metadata(outname, bounds, dem_bounds, prods_TOTbbox, dem, lat, lon, mask, outputFormat, verbose=verbose)
  File "/u/sar-r0/rzinke/python/miniconda3/envs/ARIA-tools/lib/python3.6/site-packages/ARIAtools/extractProduct.py", line 618, in finalize_metadata
    data_array = metadata_qualitycheck(data_array, os.path.basename(os.path.dirname(outname)), outname, verbose).data_array
  File "/u/sar-r0/rzinke/python/miniconda3/envs/ARIA-tools/lib/python3.6/site-packages/ARIAtools/extractProduct.py", line 415, in __init__
    self.__run__()
  File "/u/sar-r0/rzinke/python/miniconda3/envs/ARIA-tools/lib/python3.6/site-packages/ARIAtools/extractProduct.py", line 508, in __run__ 
    rsquaredarr_rng, std_errarr_rng = self.__getCovar__('range')
  File "/u/sar-r0/rzinke/python/miniconda3/envs/ARIA-tools/lib/python3.6/site-packages/ARIAtools/extractProduct.py", line 479, in __getCovar__
    if (min(rsquaredarr) < 0.9 and max(std_errarr) > 0.01) or (i[0]==(len(eval('self.data_array_band%s'%(arrT)))-1)):
ValueError: min() arg is an empty sequence

Is there anything I can do to help debug?
Thanks!

**Comment by rzinke** [comment]
For the above, I am using the most recent version of ARIA-tools:
commit c5d2844f8e6dcd27502c638f84da5d421dcf0161 (HEAD -> dev, aria-tools/dev)
Author: BB <bbuzz318@icloud.com>
Date:   Wed Aug 5 14:42:22 2020 -0700

Downloads were complete through Aug 5th.

**Comment by rzinke** [comment]
I am getting the same error for track 114 as well.

**Comment by sssangha** [comment]
@rzinke I was able to replicate this issue, and fix a bug in PR #215.

As I outline there, essentially your metadata layers were being screened for artifacts and this routine failed since originally rows and columns containing any nodata values were entired masked out so the scipy libraries leveraged for this routine would work as intended. 

This strategy has now been adjusted to just remove nodata values alone, as nothing would be left in your case where you have dozens of frames and a large amount of frame shift from top to bottom!

**Comment by rzinke** [comment]
Thanks, @sssangha! Your fix in PR #215 worked. I got a final warning:
WARNING: azimuthAngle layer for IFG 20141207_20141113 has R² of 0.0000 and standard error of 0.5912°, automated correction applied
but I think that is expected, no?

**Comment by sssangha** [comment]
@rzinke yes, that's expected as an artifact was found in your dataset. In my tests, the output appeared as a smoothly varying field. Could you also open up and confirm that is the case on your end? Thanks!

**Comment by rzinke** [comment]
@sssangha, the map view of the azimuth and incidence angles look as expected: smoothly varying between reasonable values with no artifacts or kinks. 
Many thanks.
