### ISSUE TITLE
[WANTED FEATURE] Re-running program efficiently

### ISSUE THREAD

**Issue by sssangha** [aria-tools/ARIA-tools#204]
This ticket outlines the motivation and proposed strategy behind adding in the ability to re-run the codes efficiently without restarting from scratch everytime. In the end, we should only start regenerating deleting all existing outputs from scratch when the user changes input argument (s) (i.e. different bounding box, different mask, different multilooking factor, etc.).

For each new ARIA-tools call, I propose writing a sorted dictionary of user input arguments to file (omitting the reference to the number of threads and verbose mode, which aren't relevant).
Behind this reference record, I have brainstormed a check and filter in the main ```ARIA_standardproduct``` class that is setup after the spatiotemporal sorting subfunction and behaves as outlined below for whenever a user relaunches an ARIA-tools call:
1. Compare new user inputs with the aforementioned record of user input arguments stored from the previous run. 
    - If they are the same then do a walk of the output directory to get a list of products already produced, compare it with the dictionary of IFGs passed by the class and purge references to existing products. Thus, only new IFG products are to be extracted. 
    - If certain arguments are different (e.g., mask, multilooking, etc) then regenerate all outputs from scratch.
    - However, if some specific arguments are different (e.g. specified layers, tropospheric corrections) then just generate new requested products. E.g. if a user wishes to now extract amplitude layers (whereas before only coherence was specified) then just extract the amplitude layers without regenerating coherence outputs. If tropospheric corrections were requested now and weren't before, just generate those corrections without regenerating anything else.
2. If no differences are flagged, then just print a message stating input CSV/arguments haven't changed, thus outputs have not been modified.

I envision that this routine would be a separate subfunction of the ```ARIA_standardproduct``` class that is only triggered when toggled by a separate argument in the main ```ariaExtract``` or ```ariaTSsetup``` calls, since it obviously wouldn't make sense to filter out products for ```ariaPlot``` calls which generate figures illustrating cumulative metrics.

This is the cleanest logic I could formulate at the moment, and indeed perhaps it would make more sense once I have a working version implementing such proposed changes. But if any of you have specific comments and requested features/adjustments of relevance to these efforts, please discuss them here.

**Comment by sssangha** [comment]
Storing a physical dictionary of inputs arguments would not require much overhead. However a clean, yet less transparent alternative would be to generate a unique hash and store it to a hash file that may be referenced vis-a-vis successive user inputs.

Just as a note, from what I've seen it is recommended that such a dictionary of input arguments is to be serialized as JSON before hashing. E.g.:
```
import hashlib
import json

a={'intputfile':'/path/to/file', 'bbox':'-9 9 10 12'}
print(hashlib.sha1(json.dumps(a, sort_keys=True).encode()).hexdigest())
```
Source: https://stackoverflow.com/questions/16092594/how-to-create-a-unique-key-for-a-dictionary-in-python

Any strong feelings one way or the other? I.e. for storing hash files as opposed to a full dictionary of input arguments (which should be very small anyways). I personally prefer writing out a full dictionary as I outlined above because it is more transparent, but am open to discussion.

**Comment by dbekaert** [comment]
@sssangha duplicate ticket with #198

**Comment by sssangha** [comment]
@dbekaert, ok will copy this discussion there before closing this thread.
