### ISSUE TITLE
[BUG] Cookie creation from .netrc credentials during ariaDownload.py fails.

### ISSUE THREAD

**Issue by alexdunncs** [aria-tools/ARIA-tools#205]
**Describe the bug**

Given a .netrc file in the home directory and no existing .bulk_download_cookiejar.txt file, the downloader returns the following error and prompts for credentials:

```
No existing URS cookie found, please enter Earthdata username & password:
(Credentials will not be stored, saved or logged anywhere)
 > Cookiejar is bunk: None
```

If the cookiejar file exists but is empty, it returns the following error and fails:
```
http.cookiejar.LoadError: '/home/ops/.bulk_download_cookiejar.txt' does not look like a Netscape format cookies file
```

I've confirmed that the credentials are being loaded correctly from the netrc file, so that shouldn't be the issue.
It appears that no valid cookie is being created from the credentials.

I've looked at the `ariaDownload.py`source but cannot work out where the ASFDataDload module is being loaded from so cannot debug further myself.

**To Reproduce**
```
git clone https://github.com/aria-jpl/mintpy-pge/
cd mintpy-pge
```

Create a .netrc file in the project root with valid earthdata credentials.

```
machine urs.earthdata.nasa.gov
login MYUSERNAME
password MYPASSWORD
```

```
docker build -t mintpy-sar-pge .
docker run -id --entrypoint /bin/bash --name mintpy-sar-pge mintpy-sar-pge 
docker exec -it mintpy-sar-pge /bin/bash
./run.sh
```

**Expected behavior**
Earthdata credentials are used to successfully download the data products

**Desktop:**
ARIA-tools git tag: `711465b1238166ca6e56f6d6296a67eab10245e`
OS: Ubuntu 18.04.4 LTS
Docker version 19.03.6, build 369ce74a3c

**Comment by dbekaert** [comment]
@alexdunncs: Would recommend for now that you comment out the git pull of a released version and move to dev (temporarily) till we cut a new release in the next weeks. Please let us know if that resolves the problem.

- The version you are referring to is a release: v1.1.0: 711465b1238166ca6e56f6d6296a67eab10245e
- The netrc support was committed under git commit: 35e689f53746f882065ec437cd825af729cd3e2f and has not been included in a cut release; i.e. its on dev at the moment.

**Comment by bbuzzanga** [comment]
Hi @alexdunncs, as @dbekaert said the problem should be resolved by using the dev version. There will be different error messages if there are problems with the credentials in the updated `ariaDownload.py` script.

**Comment by dbekaert** [comment]
@bbuzz31 i get further but it does not yet work for me.

with an existing netrc file still need to type password and username.


```
https://api.daac.asf.alaska.edu/services/search/param?asfplatform=Sentinel-1%20Interferogram%20(BETA)&processingLevel=GUNW_STD&output=JSON&relativeOrbit=124
Found: S1-GUNW-A-R-124-tops-20180502_20180408-043106-21658N_19755N-PP-0dd0-v2_0_1
Found: S1-GUNW-A-R-124-tops-20180502_20180408-043040-20161N_18088N-PP-6704-v2_0_1
 > Username and Password combo was not successful. Please try again.
 > attempting to download https://urs.earthdata.nasa.gov/profile
 > Could not validate old cookie Jar
No existing URS cookie found, please enter Earthdata username & password:
(Credentials will not be stored, saved or logged anywhere)
 > attempting to download https://urs.earthdata.nasa.gov/profile
Username: 
```

**Comment by dbekaert** [comment]
Actually was typo in my netrc. this seems to be all working to me.
