### ISSUE TITLE
ariaTSsetup incomplete extraction of data

### ISSUE THREAD

**Issue by yuankailiu** [aria-tools/ARIA-tools#208]
I have a track of GUNW products downloaded using the python script provided by ASF vertex search webpage. The bounding box or the area of interest was defined by dragging a rectangle on the ASF page.

I went on and used ariaTSsetup.py to extract the data from the standard products. ariaTSsetup.py was run on Jupyter:

`!time ariaTSsetup.py -f 'products/*.nc' -b '26.140 33.494 33.558 37.596' -d Download --mask Download --multilooking 10`

The output is quite normal without issue. Although there seem to be some duplicates from ASF.

> ***Time-series Preparation Function:***
> Shapefile ./user_bbox.json created for input user bounds.
> Multi-core version
> Multi-core version failed, will try single for loop
> 4 out of 2445 GUNW products rejected for not meeting user's bbox spatial criteria
> Group GUNW products into spatiotemporally continuous interferograms.
> 221 out of 2441 products rejected since they are duplicates
> All (456) interferograms are spatially continuous.
> Thread count specified for gdal multiprocessing = 2
> Download/cropping DEM
> Downloaded 3 arc-sec SRTM DEM here: ./DEM/SRTM_3arcsec.dem
> ***Downloading water mask... ***

> Extracting unwrapped phase, coherence, and connected components for each interferogram pair
> Generating: unwrappedPhase - [==================================================] 20200711_20200629    0s /     0s
> Generating: coherence - [==================================================] 20200711_20200629 2559s /    52s 

> Extracting single incidence angle, look angle and azimuth angle files valid over common interferometric grid
> Generating: incidenceAngle - [==================================================] 20141023_20141011 
> Generating: lookAngle - [==================================================] 20141023_20141011 
> Generating: azimuthAngle - [==================================================] 20141023_20141011WARNING: azimuthAngle layer for IFG 20141023_20141011 has R² of 0.5895 and standard error of 0.4935°, automated correction applied
>  
> Creating directory: ./stack
> Number of coherence discovered:  456
> [==================================================] 20200711_20190705    4s /     0s
> cohStack : stack generated
> Directory ./stack already exists.
> Number of connectedComponents discovered:  456
> [==================================================] 20200711_20190705    5s /     0s
> connCompStack : stack generated
> Directory ./stack already exists.
> Number of unwrapped interferograms discovered:  456
> [==================================================] 20200711_20200629    5s /     0s
> unwrapStack : stack generated
> 
> real	72m13.473s
> user	58m40.817s
> sys	8m50.021s

However, the result is very odd. I end up having all the extracted datasets highly incomplete. Including the unwrapped phase, downloaded DEM, and water mask file. This happens for all the dates and files. 

**Water mask:**
![image](https://user-images.githubusercontent.com/55262505/89479818-a8eddf00-d748-11ea-9981-a316eace24c1.png)

**Unwrapped phase**
![image](https://user-images.githubusercontent.com/55262505/89479841-bd31dc00-d748-11ea-8b39-2d5ccba1e554.png)

 **DEM**
![image](https://user-images.githubusercontent.com/55262505/89479861-c6bb4400-d748-11ea-9db4-8af0d5e31c4d.png)

They seem to be giving me only the overlapping region of the most northern GUNW products. 
I have the other track also with this issue, despite that the extracted data are in the middle portion. Like this:
![image](https://user-images.githubusercontent.com/55262505/89481355-65956f80-d74c-11ea-8703-f97bae62329b.png)

It worked fine before for the same region. I'd got some normal results when I ran ariaTSsetup.py for about half the amount of standard products a few months ago. Although that time I download the dataset using ariaDownload.py without giving a bounding box when downloading and extracting. Neither did I multilook the data. The unwrappedPhase.png should be like this:

![image](https://user-images.githubusercontent.com/55262505/89480847-43e7b880-d74b-11ea-90d4-3dfbc6fa4dc0.png)

I am wondering whether this is due to my bounding box or multi looking. I am trying to do the ariaTSsetup again without multilooking and see what I will get. 

`ariaTSsetup.py -f 'products/*.nc' -b '26.140 33.494 33.558 37.596' -d Download --mask Download `

**Comment by sssangha** [comment]
@liuykai I would suggest leveraging the minimum overlap (```-mo```) option to filter out shorter scenes that bias the common intersection cutline. Refer to issue ticket #161 for a detailed discussion regarding this option, and issues you may encounter without it.

Please let me know if this helps.

**Comment by dbekaert** [comment]
In addition feel free to look at this branch here as guidance wrt `-mo` and how to calculate it. Not much tested so feel free to try it out and make edits/contributions where needed. https://github.com/aria-tools/ARIA-tools-docs/blob/aria_sds/JupyterDocs/ariaEnd2End/ariaEnd2End.ipynb

The functionality exist, but documentation is limited, predominantly on the issue ticket that implemented it and on GitHub here. We welcome any contribution to integrate this in the main code and jupyter notebooks.

**Comment by dbekaert** [comment]
closing this as the provided guidance should resolve this.

**Comment by yuankailiu** [comment]
I see, @sssangha . Thanks. I looked at post #161 and found it useful. 

So because in my study area, there are some small productions (some single scene size products). We can tell from the lat_extent plot that these small products (in my case, mostly in the northernmost region) are driving the intersection criteria. So eventually, the only intersection is there.
![image](https://user-images.githubusercontent.com/55262505/89560674-41797300-d7cc-11ea-9c52-bf20898c43cc.png)


As long as we increase the minimum overlapping area, we can avoid that.

I am currently using an estimated minimum area by measuring the polygons overlapping area in QGIS. I used the .json files from the autogenerated `productBoundingBox` directory and `user_bbox.json`
![image](https://user-images.githubusercontent.com/55262505/89561085-d8dec600-d7cc-11ea-9188-7fb2dd9cc4a1.png)


Now, this is working fine. 
![image](https://user-images.githubusercontent.com/55262505/89561164-f318a400-d7cc-11ea-8ec8-360c4b52aaff.png)


@dbekaert , thanks for the link to the branch. I haven't tried the computation method from [ariaEnd2End.ipynb](https://github.com/aria-tools/ARIA-tools-docs/blob/aria_sds/JupyterDocs/ariaEnd2End/ariaEnd2End.ipynb). 

Because we will have the `productBoundingBox` directory and the `user_bbox.json` once a user runs ariaTSsetup.py with a specified bbox (-b option). It would be good to simply use these json files, then calculate and apply the best minimum overlapping area on the fly. This way, we don't need to first query the DAAC API for historic data and retrieve a CSV file with meta-data. Or perhaps I misunderstood it here.

**Comment by dbekaert** [comment]
@liuykai that is the correct observation if you have already extracted the products, likely no need to do it.  Feel free to add the other variant, would be instructive. In the end what you do is loop over all the shapefile, load them with shapely and take the union over and over to get the ground track determined. But it would imply downloading or running virtually the extract step without doing any processing. 

The daac API directly gives back all meta data in json so is relative fast < min, could be done likely directly with respect products too, but for now we pointed to the SLCS; have not tried to point it to the GUNW products

**Comment by yuankailiu** [comment]
I see. Now that makes sense to me. Thanks for clarifying it.
