### ISSUE TITLE
duplicates order of priority

### ISSUE THREAD

**Issue by dbekaert** [aria-tools/ARIA-tools#209]
If we have duplicates of v2.0.3 and before, we should give priority to v2.0.3  above the older version as it includes the bug fix for geometry information.

**Comment by EJFielding** [comment]
Seems reasonable to always give priority to the newest version number if there are multiple versions.

**Comment by EJFielding** [comment]
Now that the Nepal D019 data has been transferred to ASF, I have a large number of duplicated scenes after downloading. I was thinking it would be helpful to add a version number selection option to `ariaDownload.py`. It could save a lot of time and disk space to not download obsolete files.

**Comment by dbekaert** [comment]
The following steps are needed to make that change.
Perhaps if you feel comfortable you could try it?
Happy to check if you need help.

1. Add an argument to the argparser:
That would be here:
https://github.com/aria-tools/ARIA-tools/blob/cbd658fde4565287ab92c0550a267da59e088435/tools/bin/ariaDownload.py#L26

2. You would need to split the filename based to get the version out of it.
We keep vLarge.Medium.Small in terms of tracking the version.
Suggest you would add that here:
https://github.com/aria-tools/ARIA-tools/blob/cbd658fde4565287ab92c0550a267da59e088435/tools/bin/ariaDownload.py#L136-L138

3. Then you would just add a filter in the next lines like is done IFG
start and end-dates:
https://github.com/aria-tools/ARIA-tools/blob/cbd658fde4565287ab92c0550a267da59e088435/tools/bin/ariaDownload.py#L145-L147

That should be all you need to do to control the version.

**Comment by EJFielding** [comment]
After moving the older version `*v2_0_2.nc` files to a different directory, I still have a lot of duplicates from this track. I understand this was an AOI processed in two different ways, so it seems it ended up with duplicate scenes that have the same version but different processing hashes. The older versions are less than a quarter of the duplicates.

**Comment by dbekaert** [comment]
@EJFielding, this was related to test production on HEC where localized SLC  are used  versus S3 SLC. The full path and filename to the same SLC were different and thus let to a different hash. Really, the  "inputs" safe files did not really change just their paths.ARIA-SDS looked into this to make sure its fixed. No way to handle this in ARIA-tools different than the way we currently do. Other regions should i believe not have it wrt to hash only change.

**Comment by EJFielding** [comment]
It does not seem worth trying to add code to `ariaDownload.py` to handle the different versions if this is a special case that won't affect other datasets. It is excellent that `ariaTSsetup.py` detects and lists the duplicates, then ignores them to make a time-series input dataset without duplication.

**Comment by dbekaert** [comment]
@sssangha and @bbuzz31 believe this is accounted.
Can you detail where and how its being handled for record keeping.

**Comment by dbekaert** [comment]
@sssangha I understand this is now implemented too? If so, can you close this Issue ticket?

**Comment by sssangha** [comment]
@dbekaert that is correct, this was implemented by an earlier PR of mine this week. Handled at both the downloading stage and again captured by plotting/extracting/tssetup stage, if necessary.
