### ISSUE TITLE
support for z-shell install

### ISSUE THREAD

**Issue by dbekaert** [aria-tools/ARIA-tools#225]
Currently Z-shell install does not allow for calling the command line tools. Setting the environment manually using setenv and set in the .zshrc file does not work either, and zsh gives the error “setenv” not found. @rzinke or Niloufar, did we miss anything?

Can you also confirm that this is only related to setting of the binaries and not accessibility in python?

**Comment by dbekaert** [comment]
@nabolfat can you provide the error message you were getting and the step you did to get to the message. Did you use the setup.py program or a manually set-up?

**Comment by nabolfat** [comment]
Now that I tried both bash and Zshells, both are giving me the same error. So I don't think Zshell is giving a separate issue.
We ran the python command ,```% python ariaDownload.py -t 64```,  from the ARIA-tools/tools/bin folder directly.

**Comment by dbekaert** [comment]
To clarify during your install after repo was downloaded:

did your run the setup install commands or  are you setting the environments manually?
```
python setup.py build
python setup.py install
```

If the latter, the setenv is for cshell and not for bash or zshell, as it mentioned in the README.
If you use zshell or bash, you should be using “export” for environment variables.
https://flaviocopes.com/shell-environment-variables/

**Comment by nabolfat** [comment]
I ran the commands: 

python setup.py build
python setup.py install

**Comment by dbekaert** [comment]
@nabolfat were you able to solve this issue, if so could you contribute a small section on how to fix it?

**Comment by nabolfat** [comment]
@dbekaert
Yes, this issue was solved. Sorry for not following it up here. The problem was with the update in the installation. The details are already discussed in issue #226 .
