### ISSUE TITLE
[BUG] ASF bulk downloader error consistently occurs

### ISSUE THREAD

**Issue by rzinke** [aria-tools/ARIA-tools#251]
**Describe the bug**
When I use ```ariaDownload.py``` I have gotten this error four times in a row:

```
ASF bulk downloader error: The read operation timed out
Likely a bad handshake with the ASF DAAC. Try rerunning
```

I am not sure if there's anything to be done about it on ARIA's end. 

**To Reproduce**
1. ```ariaDownload.py -t 114 -w AllProducts```

**Desktop (please complete the following information):**
 - ARIA-tools git tag: commit cbd658fde4565287ab92c0550a267da59e088435
 - Linux CentOS (JPL sar)

**Additional context**
Perhaps it is better to run in smaller batches? Is there any routine troubleshooting you would recommend?

**Comment by dbekaert** [comment]
Try subsetting indeed. We are merely wrapping around their API.
Suggest you might also reach out to them directly.
You can use the print URL statement which is the call to their API.

Cheers,
D.

**Comment by dbekaert** [comment]
Did not hear back so closing this as a DAAC issue
