### ISSUE TITLE
gdal version no longer seems to need pinning in environment.yml

### ISSUE THREAD

**Issue by Alex-Lewandowski** [aria-tools/ARIA-tools#262]
**Describe the bug**
I was trying to create a conda env that would suport ARIA-Tools, MintPy, and ISCE2. Pinning gdal to >=3.0, <=3.0.4 caused dependency issues. I removed the pinned version, it installed gdal 3.2.1, and ARIA-Tools seems to run fine. To be more accurate, I removed gdal altogether, since conda installed it as a dependency anyhow. 

**To Reproduce**
1. Add `  - gdal >=3.0,<=3.0.4` to the attached yml and try to create a conda env with it

**Desktop (please complete the following information):**
 - ARIA-tools git tag: [e.g. git show --summary]
![image](https://user-images.githubusercontent.com/37909088/117038277-e9689200-acb3-11eb-98a6-69157c4c7986.png)
 - OS - Ubuntu 18.0.4

**Additional context**
Here is the yml (renamed as a .txt so github would allow the upload)
[insar_analysis_env.txt](https://github.com/aria-tools/ARIA-tools/files/6422621/insar_analysis_env.txt)

**Comment by bbuzzanga** [comment]
Hi @Alex-Lewandowski thanks for noticing this. @sssangha changed the gdal dependency to be just >3.1.2 in #254, which has been propagated to #261. 

I made a quick test to see if we could entirely remove gdal entirely, but codacy flagged an error. As far as I can tell, gdal isn't installed by any dependencies in ARIA-tools or MintPy, so needs to remain in our `.env`.

I think with PR #254 you should be able to install ISCE+MintPy+ARIA-tools with no problem. If you could check and let me know, that would be great.

**Comment by dbekaert** [comment]
Agreed with the above. #254 is ready to be merged.
