### ISSUE TITLE
Replacing ASF resolving urls with the final resolved

### ISSUE THREAD

**Issue by bbuzzanga** [aria-tools/ARIA-tools#264]
Currently trying to replace the ASF URLs (i.e. https://grfn.asf.alaska.edu/door/download/S1*.nc) with the final resolved URL, as per ACCESS discussion.

Any guidance on identifying the resolved URL from the output of `wget https://grfn.asf.alaska.edu/door/download/S1-GUNW-A-R-004-tops-20191214_20191202-230840-45104N_43235N-PP-af62-v2_0_2.nc` would be much appreciated.

Here is the output:

```
--2021-05-06 09:29:44--  https://grfn.asf.alaska.edu/door/download/S1-GUNW-A-R-004-tops-20191214_20191202-230840-45104N_43235N-PP-af62-v2_0_2.nc
Resolving grfn.asf.alaska.edu (grfn.asf.alaska.edu)... 35.170.204.16, 34.199.15.181, 34.192.223.184, ...
Connecting to grfn.asf.alaska.edu (grfn.asf.alaska.edu)|35.170.204.16|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://urs.earthdata.nasa.gov/oauth/authorize?app_type=401&client_id=iwntGSgHy9yoog7Mjag0dQ&response_type=code&redirect_uri=https%3A
%2F%2Fgrfn.asf.alaska.edu%2Fdoor%2Foauth&state=aHR0cDovL2dyZm4uYXNmLmFsYXNrYS5lZHUvZG9vci9kb3dubG9hZC9TMS1HVU5XLUEtUi0wMDQtdG9wcy0yMDE5MTIxNF8y
MDE5MTIwMi0yMzA4NDAtNDUxMDROXzQzMjM1Ti1QUC1hZjYyLXYyXzBfMi5uYw [following]
--2021-05-06 09:29:44--  https://urs.earthdata.nasa.gov/oauth/authorize?app_type=401&client_id=iwntGSgHy9yoog7Mjag0dQ&response_type=code&redire
ct_uri=https%3A%2F%2Fgrfn.asf.alaska.edu%2Fdoor%2Foauth&state=aHR0cDovL2dyZm4uYXNmLmFsYXNrYS5lZHUvZG9vci9kb3dubG9hZC9TMS1HVU5XLUEtUi0wMDQtdG9wc
y0yMDE5MTIxNF8yMDE5MTIwMi0yMzA4NDAtNDUxMDROXzQzMjM1Ti1QUC1hZjYyLXYyXzBfMi5uYw
Resolving urs.earthdata.nasa.gov (urs.earthdata.nasa.gov)... 2001:4d0:241a:4081::89, 198.118.243.33
Connecting to urs.earthdata.nasa.gov (urs.earthdata.nasa.gov)|2001:4d0:241a:4081::89|:443... connected.
HTTP request sent, awaiting response... 401 Unauthorized
Authentication selected: Basic realm="Please enter your Earthdata Login credentials. If you do not have a Earthdata Login, create one at https:
//urs.earthdata.nasa.gov//users/new"
Reusing existing connection to [urs.earthdata.nasa.gov]:443.
HTTP request sent, awaiting response... 302 Found
Location: https://grfn.asf.alaska.edu/door/oauth?code=50719418d6209f02f6e9ee2104dd305082dd66e84f2da150515ed0efa0ff548b&state=aHR0cDovL2dyZm4uYX
NmLmFsYXNrYS5lZHUvZG9vci9kb3dubG9hZC9TMS1HVU5XLUEtUi0wMDQtdG9wcy0yMDE5MTIxNF8yMDE5MTIwMi0yMzA4NDAtNDUxMDROXzQzMjM1Ti1QUC1hZjYyLXYyXzBfMi5uYw [f
ollowing]
--2021-05-06 09:29:45--  https://grfn.asf.alaska.edu/door/oauth?code=50719418d6209f02f6e9ee2104dd305082dd66e84f2da150515ed0efa0ff548b&state=aHR
0cDovL2dyZm4uYXNmLmFsYXNrYS5lZHUvZG9vci9kb3dubG9hZC9TMS1HVU5XLUEtUi0wMDQtdG9wcy0yMDE5MTIxNF8yMDE5MTIwMi0yMzA4NDAtNDUxMDROXzQzMjM1Ti1QUC1hZjYyLX
YyXzBfMi5uYw
Connecting to grfn.asf.alaska.edu (grfn.asf.alaska.edu)|35.170.204.16|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://grfn.asf.alaska.edu/door/download/S1-GUNW-A-R-004-tops-20191214_20191202-230840-45104N_43235N-PP-af62-v2_0_2.nc [following]
--2021-05-06 09:29:46--  http://grfn.asf.alaska.edu/door/download/S1-GUNW-A-R-004-tops-20191214_20191202-230840-45104N_43235N-PP-af62-v2_0_2.nc
Connecting to grfn.asf.alaska.edu (grfn.asf.alaska.edu)|35.170.204.16|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://grfn.asf.alaska.edu:443/door/download/S1-GUNW-A-R-004-tops-20191214_20191202-230840-45104N_43235N-PP-af62-v2_0_2.nc [following]
--2021-05-06 09:29:46--  https://grfn.asf.alaska.edu/door/download/S1-GUNW-A-R-004-tops-20191214_20191202-230840-45104N_43235N-PP-af62-v2_0_2.nc
Connecting to grfn.asf.alaska.edu (grfn.asf.alaska.edu)|35.170.204.16|:443... connected.
HTTP request sent, awaiting response... 302 FOUND
Location: https://dlz0dhr6g6ukw.cloudfront.net/S1-GUNW-A-R-004-tops-20191214_20191202-230840-45104N_43235N-PP-af62-v2_0_2.nc?userid=bbuzz&Expires=1620318601&Signature=ZAbicQesqDT-tjJl44ExTzkg9w8XWk2Z2YfTvcs3ZNP5dmvgbYxXezzjWRorIiWd4ar4MAhHOW1xRaYvP6-539eeFfzPkDugaU5mwUbwo0ngzGkfRWokZb6MS74gYTK-WhbQi-zw999XMffnu6pn~FIUQjA3Cxn2fe447Tu6nTA_&Key-Pair-Id=APKAINVNJF4BDB5SS5QQ [following]
--2021-05-06 09:29:46--  https://dlz0dhr6g6ukw.cloudfront.net/S1-GUNW-A-R-004-tops-20191214_20191202-230840-45104N_43235N-PP-af62-v2_0_2.nc?userid=bbuzz&Expires=1620318601&Signature=ZAbicQesqDT-tjJl44ExTzkg9w8XWk2Z2YfTvcs3ZNP5dmvgbYxXezzjWRorIiWd4ar4MAhHOW1xRaYvP6-539eeFfzPkDugaU5mwUbwo0ngzGkfRWokZb6MS74gYTK-WhbQi-zw999XMffnu6pn~FIUQjA3Cxn2fe447Tu6nTA_&Key-Pair-Id=APKAINVNJF4BDB5SS5QQ
Resolving dlz0dhr6g6ukw.cloudfront.net (dlz0dhr6g6ukw.cloudfront.net)... 2600:9000:201f:2800:c:792e:1400:21, 2600:9000:201f:2000:c:792e:1400:21, 2600:9000:201f:9c00:c:792e:1400:21, ...
Connecting to dlz0dhr6g6ukw.cloudfront.net (dlz0dhr6g6ukw.cloudfront.net)|2600:9000:201f:2800:c:792e:1400:21|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 69435575 (66M) [application/x-netcdf]
Saving to: ‘S1-GUNW-A-R-004-tops-20191214_20191202-230840-45104N_43235N-PP-af62-v2_0_2.nc’

S1-GUNW-A-R-004-tops-20191214_20191 100%[==================================================================>]  66.22M  4.32MB/s    in 9.6s

2021-05-06 09:29:56 (6.91 MB/s) - ‘S1-GUNW-A-R-004-tops-20191214_20191202-230840-45104N_43235N-PP-af62-v2_0_2.nc’ saved [69435575/69435575]
```

**Comment by bbuzzanga** [comment]
We'd hope we could simply grab the last URL, but that doesn't seem to work:
```
wget https://dlz0dhr6g6ukw.cloudfront.net/S1-GUNW-A-R-004-tops-20191214_20191202-230840-45104N_43235N-PP-af62-v2_0_2.nc?userid=bbuzz&Expires=1620318601&Signature=ZAbicQesqDT-tjJl44ExTzkg9w8XWk2Z2YfTvcs3ZNP5dmvgbYxXezzjWRorIiWd4ar4MAhHOW1xRaYvP6-539eeFfzPkDugaU5mwUbwo0ngzGkfRWokZb6MS74gYTK-WhbQi-zw999XMffnu6pn~FIUQjA3Cxn2fe447Tu6nTA_&Key-Pair-Id=APKAINVNJF4BDB5SS5QQ
[1] 37976
[2] 37977
[3] 37978
bash: Key-Pair-Id=APKAINVNJF4BDB5SS5QQ: command not found
[2]   Done                    Expires=1620318601
[3]+  Done                    Signature=ZAbicQesqDT-tjJl44ExTzkg9w8XWk2Z2YfTvcs3ZNP5dmvgbYxXezzjWRorIiWd4ar4MAhHOW1xRaYvP6-539eeFfzPkDugaU5mwUbwo0ngzGkfRWokZb6MS74gYTK-WhbQi-zw999XMffnu6pn~FIUQjA3Cxn2fe447Tu6nTA_```

**Comment by asjohnston-asf** [comment]
ASF here.  The final distribution URL is a [CloudFront signed URL](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-signed-urls.html) that is only valid for 15 seconds.  They're generated dynamically with each request.  As things are currently implemented you won't be able to predict what the final resolved download URL will be, and you won't be able to cache/reuse the final download URL after it's been resolved.

Can you provide any additional context for what you're trying to accomplish?

**Comment by bbuzzanga** [comment]
Hi @asjohnston-asf thanks for the info. We were hoping that the CloudFront URL was valid for much longer, and that we could then do our processing with those URLs instead of the self-resolving ones. Our working hypothesis is that the virtual data processing is taking longer than physically downloading it because of the URL redirects. Looks like this is a dead end though, thanks.

**Comment by asjohnston-asf** [comment]
The authentication component can take a second or two per request, so you'd definitely want to re-use any cookies across subsequent requests to avoid having to re-authenticate with every request.  If you're already authenticated, I'd expect the one redirect to the signed url to only take tens of milliseconds, maybe hundreds of milliseconds.

**Comment by asjohnston-asf** [comment]
For example, in your initial post, there are a total of seven URLs invoked.  If you were already authenticated (via --save-cookies and --load-cookies, for example), that would be reduced to only final two.

**Comment by dbekaert** [comment]
@asjohnston-asf 

 > Can you provide any additional context for what you're trying to accomplish?

As part of the NASA ACCESS cloud enabling InSAR science proposal that JPL-ASF was awarded we are trying to identify and adress some of these bottlenecks. In short we are trying to find out more efficient ways to process alongside the data while removing the need for actual download. Currently we are testing this for the GRFN data eventually will do the same for Sentinel-1 etc.

To enable along side data processing in the cloud we are trying to get rid of the overhead related to the self-resolving URLS. For each meta-data field we access using GDAL we believe the URL needs to be resolved. Currently virtual data processing is much slower than if we were to download the data and perform the processing.  In our use-case we  touch the same GRFN products  multiple times with perhaps processing that can be as short as a few minutes to  few hours.

The processing gets only executed at the end of the workflow. Some users could invoke the final step perhaps days after the virtual files were created.

>  If you were already authenticated (via --save-cookies and --load-cookies, for example), that would be reduced to only final two.

The example that @bbuzz31 copied above was a manual call on command line to see if he could find the URL.  Do you have any guidance how one might be able to set the save cookies field and load cookies fied in GDAL? We are setting them as based in our earlier issue ticket here: Support virtual file access #138

```
export GDAL_HTTP_COOKIEFILE=/tmp/cookies.txt
export GDAL_HTTP_COOKIEJAR=/tmp/cookies.txt
export VSI_CACHE=YES
```

**Comment by asjohnston-asf** [comment]
Thanks for the context, that helps a lot.

Those are the cookie variables I was going to suggest for /vsicurl, so you're probably already good there.  Disregard my fears of re-authenticating multiple times.

I agree if you're making many requests against the file, the redirect processing could hurt performance.  As an experiment, I've uploaded that same file to a public URL, without any authentication or redirects:

https://asj-hyp3-dev.s3-us-west-2.amazonaws.com/door/download/S1-GUNW-A-R-004-tops-20191214_20191202-230840-45104N_43235N-PP-af62-v2_0_2.nc

If you run your workflow against that URL, how does performance compare with the grfn.asf.alaska.edu URL?

**Comment by dbekaert** [comment]
@asjohnston-asf did not yet have the time to look at this, we are targeting this next.

**Comment by bbuzzanga** [comment]
Thanks for uploading, surprisingly it's still quite a bit slower. 
Would you be able to upload a few more products so I can check on time series prep?

![Screen Shot 2021-05-20 at 4 17 09 PM](https://user-images.githubusercontent.com/15522503/119060356-e0034900-b986-11eb-9c93-463b907fb2fe.png)

**Comment by asjohnston-asf** [comment]
Sure, if you post a list of scenes I can make them available

**Comment by bbuzzanga** [comment]
Great, thanks!
```
https://grfn.asf.alaska.edu/door/download/S1-GUNW-A-R-004-tops-20200307_20200212-230634-37654N_35778N-PP-e0ac-v2_0_2.nc
https://grfn.asf.alaska.edu/door/download/S1-GUNW-A-R-004-tops-20200307_20200224-230634-37654N_35778N-PP-8115-v2_0_2.nc
https://grfn.asf.alaska.edu/door/download/S1-GUNW-A-R-004-tops-20200224_20200131-230634-37654N_35777N-PP-c2a8-v2_0_2.nc
https://grfn.asf.alaska.edu/door/download/S1-GUNW-A-R-004-tops-20200224_20200212-230634-37654N_35777N-PP-e269-v2_0_2.nc
https://grfn.asf.alaska.edu/door/download/S1-GUNW-A-R-004-tops-20200212_20200107-230634-37655N_35778N-PP-ea57-v2_0_2.nc
https://grfn.asf.alaska.edu/door/download/S1-GUNW-A-R-004-tops-20200212_20200131-230634-37655N_35778N-PP-9023-v2_0_2.nc
https://grfn.asf.alaska.edu/door/download/S1-GUNW-A-R-004-tops-20200131_20200107-230634-37654N_35778N-PP-c7b9-v2_0_2.nc

**Comment by asjohnston-asf** [comment]
Done, all eight scenes are available via
```
https://asj-hyp3-dev.s3-us-west-2.amazonaws.com/door/download/S1-GUNW-A-R-004-tops-20191214_20191202-230840-45104N_43235N-PP-af62-v2_0_2.nc
https://asj-hyp3-dev.s3-us-west-2.amazonaws.com/door/download/S1-GUNW-A-R-004-tops-20200131_20200107-230634-37654N_35778N-PP-c7b9-v2_0_2.nc
https://asj-hyp3-dev.s3-us-west-2.amazonaws.com/door/download/S1-GUNW-A-R-004-tops-20200212_20200107-230634-37655N_35778N-PP-ea57-v2_0_2.nc
https://asj-hyp3-dev.s3-us-west-2.amazonaws.com/door/download/S1-GUNW-A-R-004-tops-20200212_20200131-230634-37655N_35778N-PP-9023-v2_0_2.nc
https://asj-hyp3-dev.s3-us-west-2.amazonaws.com/door/download/S1-GUNW-A-R-004-tops-20200224_20200131-230634-37654N_35777N-PP-c2a8-v2_0_2.nc
https://asj-hyp3-dev.s3-us-west-2.amazonaws.com/door/download/S1-GUNW-A-R-004-tops-20200224_20200212-230634-37654N_35777N-PP-e269-v2_0_2.nc
https://asj-hyp3-dev.s3-us-west-2.amazonaws.com/door/download/S1-GUNW-A-R-004-tops-20200307_20200212-230634-37654N_35778N-PP-e0ac-v2_0_2.nc
https://asj-hyp3-dev.s3-us-west-2.amazonaws.com/door/download/S1-GUNW-A-R-004-tops-20200307_20200224-230634-37654N_35778N-PP-8115-v2_0_2.nc
```

**Comment by dbekaert** [comment]
closing this as not possible. We will pursue the discussion through JPL-ASF ACCESS proposal and future directions
