### ISSUE TITLE
issue when running ariaDownload.py -h

### ISSUE THREAD

**Issue by ulloa18** [aria-tools/ARIA-tools#271]
Hi,

I am trying to install and run Aria-tools on an Ubuntu 21.04 VM (Windows 10 Host). 
I followed the steps mentioned in the ReadMe file:

- clone git repo
- create new environment with anaconda using environment.yml
- activate new environment
- install all the dependencies
- build and installing using setup.py file
- saving to PYTHONPATH and PATH

The problem I encounter is that when I run on a Jupyter Notebook:
!ariaDownload.py -h

I get the error;
Traceback (most recent call last):
  File "/usr/local/bin/ariaDownload.py", line 19, in <module>
    import matplotlib as mpl
ModuleNotFoundError: No module named 'matplotlib'

However, I am sure matplotlib is install in such environment because I can import it in another cell.

Additionally, if I try to import ARIAtools directly I get the error:
 
ModuleNotFoundError: No module named 'ARIAtools'

Thanks

**Comment by bbuzzanga** [comment]
hi @ulloa18, you need to install to the created conda environment and use it. `File "/usr/local/bin/ariaDownload.py", line 19` indicates a problem in your conda setup

**Comment by dbekaert** [comment]
We have not tested ARIA-tools on Windows. 
- If you are setup.py with build and install, then there should be no need to set the python path and path.
- If you are using setup.py with just build, then you would need to add the PATH and PYTHON PATH

Can you provide additional information on how you are installing perhaps with the command you use?

**Comment by dbekaert** [comment]
closing it as no additional details provided. Can be re-opened if needed

**Comment by KASHKASHOPTIMUS** [comment]
I am using GIT BASH in windows, having the same problem though i save the path and python path the jupyter notebook. please can someone confirm the way of saving path and python path i feel i might have made a mistake there.
![111](https://user-images.githubusercontent.com/107583734/174967617-86a33682-8f44-478b-af8a-bbee4548bdf0.JPG)

**Comment by KASHKASHOPTIMUS** [comment]
![677](https://user-images.githubusercontent.com/107583734/174968101-3e686f1e-b120-4c52-a61f-cfe58d4e95a5.JPG)
please can someone explain how to do the second half of this paragraph
