### ISSUE TITLE
[BUG] GACOS products aren't applied

### ISSUE THREAD

**Issue by bbuzzanga** [aria-tools/ARIA-tools#276]
Applying GACOS products fails

Issue 1
GACOS products are distributed (or at least I received) `.tif` files.
`tropo_correction` in `extractProduct.py` only counts `.vrt` extensions as valid files.
I implemented a workaround for this.

Issue 2 
`tropo_correction` in `extractProduct.py` looks to extract metadata from `.rsc` files that are not present. 

These function is rife with nested list comprehensions and very difficult to debug.
@sssangha recently used GACOS for San Diego, could you have a look?

```Traceback (most recent call last):
  File "/Users/bb/Miniconda3/envs/ARIA/bin/ariaTSsetup.py", line 18, in <module>
    main(inps)
  File "/Users/bb/Miniconda3/envs/ARIA/lib/python3.8/site-packages/ARIAtools/tsSetup.py", line 541, in main
    tropo_correction(standardproduct_info.products, inps.tropo_products,
  File "/Users/bb/Miniconda3/envs/ARIA/lib/python3.8/site-packages/ARIAtools/extractProduct.py", line 937, in tropo_correction
    tropo_rsc_dict['TIME_OF_DAY']= open(j[:-4]+'.rsc', 'r'
FileNotFoundError: [Errno 2] No such file or directory: '/Volumes/BB_4TB/data/VLM/Sentinel1/track_150/Results/Charleston_GACOS/GACOS/20160419.ztd.rsc'

**Comment by sssangha** [comment]
@bbuzz31 I could go ahead and replicate what I implemented to handle the new tif formats that are distributed through GACOS (https://github.com/insarlab/MintPy/commit/6c85534f104f92f7b70c305ce85dcad4f19d6aa6#diff-018e1d39e3d396c6ccac133a8f25b924a12f16bc84f5409b5186edf52a4d7929) but it looks like I can't access the data I used to debug that PR.

Could you please send me a couple of example GACOS products + the corresponding commandline inputs I'd need to access /prep some of the ARIA products you are using?

Thanks

**Comment by bbuzzanga** [comment]
@sssangha thanks for having a look. I sent you a folder via email with what you need

**Comment by sssangha** [comment]
@bbuzz31 check out the updates to PR #275 

I added support for the new TIF files.

Unfortunately, the TIF files no longer track the UTC times so for these products the code is unable to confirm whether or not the products are within the range of expected time vis-a-vis the standard product acquisition times. So until this is potentially resolved on the GACOS end, it is the user's responsibility to not mix up the GACOS products.

**Comment by bbuzzanga** [comment]
@sssangha thanks! LGTM
