### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'asf_search'

### ISSUE THREAD

**Issue by EJFielding** [aria-tools/ARIA-tools#288]
**Describe the bug**
The ariaDownload script is trying to import 'asf_search'.
ModuleNotFoundError: No module named 'asf_search'

**To Reproduce**
1. I ran a git pull to get latest version, activated the environment, and then ran 'python setup.py install'.
2.  ariaDownload.py -b '37.25 38.1 -122.6 -121.75' --track 42
```
Traceback (most recent call last):
  File "/Users/fielding/anaconda3/envs/ARIA-tools/bin/ariaDownload.py", line 16, in <module>
    import asf_search as asf
ModuleNotFoundError: No module named 'asf_search'
```
**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - ARIA-tools git tag: [e.g. git show --summary]commit 0251a1dce5230378a2391e54467343e662fdfadf (HEAD -> dev, origin/dev, origin/HEAD)
Author: BB <bbuzz318@icloud.com>
Date:   Mon Nov 29 11:05:23 2021 -0800
 - OS: I tried on both MacOS and Linux (NISAR On-demand system)

**Additional context**

**Comment by bbuzzanga** [comment]
Hi @EJFielding, since you're using an existing environment the updates to the environmental file won't automatically install.

However, `conda install asf_search` in your activated environment should fix the problem

**Comment by EJFielding** [comment]
Thanks for the quick reply @bbuzz31. That worked on my MacOS installation that I had not used for many months and only updated now. 

The NISAR on-demand environment setup is supposed to include everything but I guess that was added recently.

**Comment by EJFielding** [comment]
On the NISAR on-demand system I had to run `conda install -c conda-forge asf_search`

**Comment by EJFielding** [comment]
I had some downloads fail due to connection reset. I am rerunning the download and the `aria_search` complains that the files exist:
```
ARIA-tools Version: 1.1.0
Traceback (most recent call last):
  File "/home/jovyan/.local/envs/mintpy/bin/ariaDownload.py", line 293, in <module>
    Downloader(inps)()
  File "/home/jovyan/.local/envs/mintpy/bin/ariaDownload.py", line 260, in __call__
    scenes.download(self.inps.wd, processes=nt)
  File "/home/jovyan/.local/envs/mintpy/lib/python3.9/site-packages/asf_search/ASFSearchResults.py", line 32, in download
    product.download(path=path, session=session)
  File "/home/jovyan/.local/envs/mintpy/lib/python3.9/site-packages/asf_search/ASFProduct.py", line 38, in download
    download_url(url=self.properties['url'], path=path, filename=filename, session=session)
  File "/home/jovyan/.local/envs/mintpy/lib/python3.9/site-packages/asf_search/download/download.py", line 61, in download_url
    raise ASFDownloadError(f'File already exists: {os.path.join(path, filename)}')
asf_search.exceptions.ASFDownloadError: File already exists: /home/jovyan/SolidEarth/ATBD/jupyter/interseismic/interseimicSanFrancisco/products/S1-GUNW-D-R-042-tops-20210802_20210715-140737-38459N_36646N-PP-acf2-v2_0_4.nc
```
I am going to open a new issue about this as I got the same result on my Mac.
