### ISSUE TITLE
gdal3, mintpy, basemap etc

### ISSUE THREAD

**Issue by piyushrpt** [aria-tools/ARIA-tools#29]
See insarlab/MintPy#83

1. Might be a good idea to explicitly add >=3.6 to python requirement
2. Setting PROJ_LIB using pyproj.pyproj_datadir will remove conflicts with basemap

**Comment by dbekaert** [comment]
basemap has been replaced with cartopy. Closing this issue as requirement no longer conflicts

**Comment by dbekaert** [comment]
Solution that works but no longer used:
```
import pyproj
```

 Defining the home and data directories at the processing location
```
home_dir = os.getcwd()
tutorial_home_dir = os.path.abspath(os.path.join(home_dir, ""))
data_dir = os.path.join(tutorial_home_dir,'data')
print("home directory: ", tutorial_home_dir)
print("")
```

loading the proj directories for GDAL and pyproj seperate as they are incompatible
Untill basemap is cought up with proj6 we will use a workaround.
We will swap to pyproj basemap proj version just before plotting.
```
pyproj_proj_path = pyproj.datadir.pyproj_datadir
GDAL_proj_path =  os.environ.get('PROJ_LIB')
print("Workaround for basemap and GDAL incompatability of PROJ4: ")
print("GDAL PROJ4 version:" + GDAL_proj_path)
print("Basemap PROJ4 version: " + pyproj_proj_path)
```
