### ISSUE TITLE
[BUG] DEM download now requires an API Key

### ISSUE THREAD

**Issue by bbuzzanga** [aria-tools/ARIA-tools#292]
The changes upstream at open Topo prevent us from downloading SRTM dems without an API Key.
- See: https://opentopography.org/developers

We now have to add the custom API_Key to the URL string of our DEM, i.e.,:
```
_world_dem = "https://portal.opentopography.org/API/globaldem?demtype="\
               "SRTMGL1_E&west={}&south={}&east={}&north={}&outputFormat=GTiff"
_world_dem += '&API_Key=yourapikey'
```
This is no problem.

However, we will need to decide how we want the user to store their keys for us to access them.
It seems the common secure ways are to 
1) store the key in a file 
2) store it in an environment variable.

Either way is fine I think. Copernicus data service uses the former. 
Does anyone have any strong opinions? We will need to update the installation documents pronto.

**Comment by sssangha** [comment]
PR #293  implements the former option, specifically aria-tools now accesses the API key from a `~/.topoapi` file... The installation section of the readme is also updated to reflect definition of this `~/.topoapi` file
