### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by yaohanze** [aria-tools/ARIA-tools#297]
**Describe the bug**
computeMisclosure.py has a bug in the definition of stack class.

**To Reproduce**
With current code, initialize a new stack object will raise the error stack project doesn't have attribute 'verbose'.
So I check the code of computeMisclosure.py starting from line 132.
After adding this line "self.verbose = verbose", the problem is fixed.

**Comment by rzinke** [comment]
Thank you for pointing that out and suggesting a fix, @yaohanze. I uncovered another bug and I'm fixing that now.

**Comment by bbuzzanga** [comment]
Hey @rzinke can you update on status? Is this fixed as part of https://github.com/aria-tools/ARIA-tools/pull/298 or does more need to be done?

**Comment by rzinke** [comment]
Issue is fixed with #298.

**Comment by bbuzzanga** [comment]
Issue is fixed in #306
