### ISSUE TITLE
"/usr/bin/sh: 1: ariaDownload.py: not found"

### ISSUE THREAD

**Issue by hekungeo** [aria-tools/ARIA-tools#304]
Hi

I am using the ariaDownload_tutorial.ipynb.
and it shows "/usr/bin/sh: 1: ariaDownload.py: not found"

I have finished the steps mentioned in the ReadMe file.

Did I put the ARIA-tools folder in the wrong directory?

Thanks in advance.

**Comment by bbuzzanga** [comment]
If you installed ariaTools via the recommended `python -m pip install . ` then you likely didn't activate the conda environment before running the jupyter notebook.

If you installed another way, you will need to make sure that the bin folder containing `ariaDownload.py` is on your system path (check with `echo $PATH` on linux)
