### ISSUE TITLE
Update mode: SetMetadataItem

### ISSUE THREAD

**Issue by rzinke** [aria-tools/ARIA-tools#307]
**Describe the bug**
I am trying to prepare a series of ARIA standard products for timeseries processing. The products come from Tibet track 150.
A-T makes it through most of the necessary layers, but then barfed when attempting to create the perpendicular baseline layer.

```
Generating: incidenceAngle - [==================================================] 20170402_20170321
Generating: lookAngle - [==================================================] 20170402_20170321
Generating: azimuthAngle - [==================================================] 20170402_20170321
Traceback (most recent call last):
  File "/home/rzinke/miniconda3/envs/insar/bin/ariaTSsetup.py", line 18, in <module>
    main(inps)
  File "/home/rzinke/miniconda3/envs/insar/lib/python3.10/site-packages/ARIAtools/tsSetup.py", line 558, in main
    ref_dlist = generate_stack(standardproduct_info, 'unwrappedPhase',
  File "/home/rzinke/miniconda3/envs/insar/lib/python3.10/site-packages/ARIAtools/tsSetup.py", line 188, in generate_stack
    b_perp = extract_meta_dict(aria_prod, 'bPerpendicular')
  File "/home/rzinke/miniconda3/envs/insar/lib/python3.10/site-packages/ARIAtools/tsSetup.py", line 149, in extract_meta_dict
    stat = data_set.GetRasterBand(1).GetStatistics(True, True)
  File "/home/rzinke/miniconda3/envs/insar/lib/python3.10/site-packages/GDAL-3.5.0-py3.10-linux-x86_64.egg/osgeo/gdal.py", line 3535, in GetStatistics
    return _gdal.Band_GetStatistics(self, *args)
RuntimeError: netCDFRasterBand::SetMetadataItem() can only be called in update mode
```

**To Reproduce**
This could be difficult to reproduce due to the large number of files involved. I am working on a reproducible set of steps now.

**Desktop (please complete the following information):**
 - ARIA-tools git tag: a56a8e538769a7c7883ad5922d2f12227344a15e
 - OS: Ubuntu 20.04.4 LTS

**Comment by bbuzzanga** [comment]
this is a result of the recent update to GDAL (3.4.2 I think?) and addressed (for now) in this https://github.com/aria-tools/ARIA-tools/pull/306

The temporary fix is just forcing gdal < 3.4.2 in the environment file. You can try to do `conda install gdal=3.4.2` in your current environment but I find this can mess up library bindings.

Recommend you pull [that](https://github.com/aria-tools/ARIA-tools/pull/306) and use the environment file to start fresh

**Comment by sssangha** [comment]
@rzinke I've tried out the changes Brett made to the environment and it works on my end. As a sanity check, could you please confirm on your end and then close this ticket? Thanks!

**Comment by rzinke** [comment]
Thanks @bbuzz31 and @sssangha , I am verifying now.

**Comment by rzinke** [comment]
Reinstalling with the PR #306 did the trick. Thanks.

**Comment by sssangha** [comment]
@rzinke looks like this had been resolved. Will close the ticket.

**Comment by bbuzzanga** [comment]
reopening as forcing an older gdal version not a satisfactory solution

**Comment by KASHKASHOPTIMUS** [comment]
I am facing the same issue, applied PR #306 but issue not resolved

**Comment by bbuzzanga** [comment]
You’ll need to reinstall ARIA-tools into a fresh conda environment, or manually try to downgrade gdal in the existing environment with ARIA-tools (e.g., conda install `gdal=3.4.2`)

**Comment by KASHKASHOPTIMUS** [comment]
The environment file is taking so long to run. Why is that?

Thanks & Regards,
Kashyap
________________________________

**Comment by KASHKASHOPTIMUS** [comment]
I followed the instruction and reinstalled everything but this time ARIAtools egg_info is not in the folder also when I run the setup.py in the tools/ARIAtools folder I get the following error
![1223](https://user-images.githubusercontent.com/107583734/181352704-11207330-ef59-4a55-98bd-34a2e51b6b80.JPG)

**Comment by bbuzzanga** [comment]
Please follow instructions per readme. you shouldn't be manually running setup.py. Use  `python -m pip install .`

Note that we don't test on windows.

**Comment by KASHKASHOPTIMUS** [comment]
I tried that too giving me the same error

Thanks & Regards,
Kashyap
________________________________

**Comment by bbuzzanga** [comment]
You can now try to pull this fix: https://github.com/aria-tools/ARIA-tools/pull/314. Recommend to reinstall from as clean an install as you can.

**Comment by WalternativE** [comment]
@bbuzz31 does this fix only work with the newest version of `gdal` or also with versions prior to `3.5.1`. I tried to run the `ariaTSsetup_tutorial`  notebook in the `ARIA-tools-docs` with the newest version of `ARIA-tools` both with `gdal` versions `3.4.2` and `3.4.3` without success. I haven't yet tried to upgrade to `>= 3.5.1` as the environment I'm running has a lot of moving parts in it.

**Comment by bbuzzanga** [comment]
@ssangha implemented this fix

**Comment by sssangha** [comment]
@WalternativE as @bbuzz31 said, please try to reinstall with the newest dev branch, also making sure to update your environment with the new `environment.yml` file. Please let me know if this resolves the issue on your end

**Comment by WalternativE** [comment]
@sssangha I fear that this isn't possible for me because I would use it together with `isce2` which does not support `gdal` versions greater than `2.4.x` for its latest release. I assume until this conflict resolves in the feature it would be best to have separate environments for different parts of the workflow, right?

**Comment by KASHKASHOPTIMUS** [comment]
I am using ariaTSsetup script for preparing time series, the script works but tif output does not seem to be supported by gdal. 
![MicrosoftTeams-image (23)](https://user-images.githubusercontent.com/107583734/183713806-e604f2a4-7029-43ac-abdb-6cea12bfe35b.png)

**Comment by bbuzzanga** [comment]
> I am using ariaTSsetup script for preparing time series, the script works but tif output does not seem to be supported by gdal. ![MicrosoftTeams-image (23)](https://user-images.githubusercontent.com/107583734/183713806-e604f2a4-7029-43ac-abdb-6cea12bfe35b.png)

I suspect your openTopo is not configured correctly. What is inside the contents of the SRTM files?

Please move to separate issue if not related to SetMetadataItem.

**Comment by KASHKASHOPTIMUS** [comment]
The SRTM file seems to be damaged or corrupt as no image is generated. please let me know what other info do you need?The first line of the picture shows how topo api key is set 
![MicrosoftTeams-image (24)](https://user-images.githubusercontent.com/107583734/183750006-c193dd2a-a5a1-463c-856f-09dfdc7aa48b.png)

**Comment by WalternativE** [comment]
@KASHKASHOPTIMUS  the `.topoapi` file should be in your home directory (so I'd just pipe to `~/.topoapi`). I'd also generate a new API key if I were you. Don't know if the bots are crawling images as well on GitHub but one can never be completely sure. For further debugging it would be good if you could create another issue as bbuz31 said. There might be more questions which aren't connected to the problem of this thread.

**Comment by KASHKASHOPTIMUS** [comment]
Thank you for the advice! I was wondering if there is a problem with the DEMfilename as it has a forward and a backward slash in its name. I shall create a new issue. Thanks

**Comment by bbuzzanga** [comment]
> The SRTM file seems to be damaged or corrupt as no image is generated. please let me know what other info do you need?The first line of the picture shows how topo api key is set ![MicrosoftTeams-image (24)](https://user-images.githubusercontent.com/107583734/183750006-c193dd2a-a5a1-463c-856f-09dfdc7aa48b.png)

To clarify, I meant open the tif file with a texteditor., e.g., `vi SRTM_3arsec_uncropped.tif` and let us know the results. (Preferably in a new ticket, thanks @WalternativE)

**Comment by bbuzzanga** [comment]
setMetaDataItem is addressed in https://github.com/aria-tools/ARIA-tools/pull/318
openTopo is addressed in https://github.com/aria-tools/ARIA-tools/issues/322
