### ISSUE TITLE
[BUG] SRTM_3arcsec_uncropped.tif not recognized as supported file

### ISSUE THREAD

**Issue by KASHKASHOPTIMUS** [aria-tools/ARIA-tools#322]
**Invalid API key**
When I ran the ariaTSsetup.py on Anaconda prompt to process netcdf (.nc) files to make time series data. The DEM file which is an output from a code within the script gives a runtime error. When I check the DEM file by opening it on a notepad there seems to be an invalid API key ERROR.

**To Reproduce**
1. Follow the setup process as mentioned on the github page for aria-tools on an anaconda prompt command line
2. After installation go to ARIA-tools>tools>bin folder and run python ariaDownload.py -w (paste working directiory Nisar>L2_interseismic folder) -u (username) -p (password) -b (houston area bounding box) -m 30 -l 36 -s 20180101 -e 20211231 -o Download
3. After Downloading rub python ariaTSsetup.py -f (paste L2_interseismic folder) --mask Download
4. The image of the error is attached 

OS- WINDOWS 10 
Mode of install and use- anaconda prompt and jupyter notebook

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - ARIA-tools git tag: [e.g. git show --summary]
 - OS
![MicrosoftTeams-image (27)](https://user-images.githubusercontent.com/107583734/184697712-c7c46c18-9d9d-4dcb-913f-3e9d78193e85.png)

![MicrosoftTeams-image (26)](https://user-images.githubusercontent.com/107583734/184697694-d94eb3c2-e3f3-444f-a115-743fead55371.png)

**Additional context**

**Comment by bbuzzanga** [comment]
You haven't configured your api key for open topo. Follow installation instructions under heading: `REQUIRED: Acquire API key to access/download DEMs`
