### ISSUE TITLE
SmallbaselineApp.py cannot find ifgram.hd5 file

### ISSUE THREAD

**Issue by KASHKASHOPTIMUS** [aria-tools/ARIA-tools#324]
**To Reproduce**
1. Run commands as per instructions given in jupyter docs for Insar time series analysis using mintpy and aria products
2. On Anaconda Prompt run command python ariaDownload.py -b "29.465237 30.051789 -96.253476 -94.613767" -m 30 -l 36 -s 
20180101 -e 20211231 -o Download
3. After download another command on the anaconda prompt python ariaTSsetup.py -f L2_interseismic directory --mask Download 
4. After geometric and interferrograms stacks are generated, we need to post location of these files on a configuration file that are used with smallbaselineApp.py command. -> smallbaselineApp.py Houston_validation.txt --dostep load_data

**Expected behavior**
The output of the script is ifgram.h5 hdf5 file and geometric hfd5 file which are used to prepare time series 
![cxv](https://user-images.githubusercontent.com/107583734/185198209-3ff91ab4-1489-4f78-814e-f58a121aa319.JPG)
![bnmn](https://user-images.githubusercontent.com/107583734/185198437-c0fc3b1c-40cc-4770-b5b7-08b700d1ac98.JPG)

 - working on anaconda prompt windows 10

**Comment by KASHKASHOPTIMUS** [comment]
The second image is the configuration file for smallbaselineApp.py

**Comment by ehavazli** [comment]
This issue is related to MintPy. 
It looks like ARIA-tools does what it is supposed to do. Please open this ticket in the MintPy repo.
