### ISSUE TITLE
!ariaDownload.py cant download DESCENDING products?

### ISSUE THREAD

**Issue by MHMoazezian** [aria-tools/ARIA-tools#327]
HI 
I use : "!ariaDownload.py --bbox '30.954987 31.046605 56.354506 56.485358' --workdir data/products --track 166 --start 20181223 --end 20211125 --daysless 73 --daysmore 0" and get 0 product buy there are in Alaska.asf 
but when I use track 57 ( ASCENDING) there are many products.

**Comment by bbuzzanga** [comment]
There are no sentinel 1 products in that bbox. They are only available on track 166 in ~southwest U.S. 
Perhaps you were search Sentinel-1 data instead of ARIA interferograms (S1 InSAR on ASF vertex)
