### ISSUE TITLE
[BUG] Problem: nothing provides __glibc version

### ISSUE THREAD

**Issue by jlmaurer** [aria-tools/ARIA-tools#330]
**Describe the bug**
Running: `conda env create -f environment.yml`
after a clean download of the current repo gives the following error: 

`Problem: nothing provides __glibc >=2.17,<3.0.a0 needed by libgdal-3.4.2-h0e87c58_6`

INFO:
 - ARIA-tools git tag: 
 commit 844fa0dc6d33c589198aae549e08d400a55156b6 (HEAD -> dev, origin/dev, origin/HEAD)
Merge: a7399f4 155d78d
Author: Simran S Sangha <sssangha@ucla.edu>
Date:   Fri Aug 19 13:52:12 2022 -0700

    Merge pull request #326 from bbuzz31/regex2
    
    more robust version handling

 - OS
Ubuntu 20.04.5 LTS

Any ideas?

**Comment by dbekaert** [comment]
@sssangha @bbuzz31 can you look into this?

**Comment by sssangha** [comment]
In the env, gdal is now unpinned, so this issue is resolved.
