### ISSUE TITLE
[WANTED FEATURE] Check whether DEM is relative to geoid or ellipsoid

### ISSUE THREAD

**Issue by rzinke** [aria-tools/ARIA-tools#333]
**Is your feature request related to a problem? Please describe.**
One must be very careful when providing a bring-your-own DEM to ARIA-tools. From [this thread](https://github.com/aria-tools/ARIA-tools/issues/237#issuecomment-728634864), it appears that AT assumes the B.Y.O. DEM values are relative to the ellipsoid, rather than the geoid. For the uninitiated, this difference might seem arbitrary. Even for those familiar with the difference, checking what the DEM is relative to can be difficult.

**Describe the solution you'd like**
Subroutine of `prep_dem` should check which datum (ellipsoid/geoid) is used, and apply ellipsoid correction if necessary.

**Describe alternatives you've considered**
Flag in `prep_dem` reminding user that ellipsoid correction is needed.

**Additional context**
Difference is ~30 m in parts of western N America.

**Comment by dbekaert** [comment]
@rzinke perhaps as a stopgap measure would be to implement the check and error out with the message. Is that something you could contribute as a PR?
