### ISSUE TITLE
[BUG] Coherence maps not multilooked

### ISSUE THREAD

**Issue by rzinke** [aria-tools/ARIA-tools#352]
**Describe the bug**
`ariaTSsetup.py` does not properly multilook the coherence images.

**To Reproduce**
Applies to all data sets.

**Expected behavior**
When running `ariaTSsetup.py` with an argument passed to the multilook option, the `export_products` function should multilook all datasets. Instead, the coherence map does not appear to be downsampled or multilooked.

This is confirmed using `gdalinfo | grep "Pixel Size"` for a connected components file, which returns:
```
Pixel Size = (0.007501111605158,-0.007500000000000)
```

whereas doing the same for a coherence file returns:
```
Pixel Size = (0.002500000000000,-0.002500000000000)
```
(1/3 the dimension).

This leads to the behavior described in [MintPy Issue ticket 972](https://github.com/insarlab/MintPy/issues/972).

I will attempt to debug this week, time allowing.

**Comment by rzinke** [comment]
Perhaps the issue is somewhere here:
https://github.com/aria-tools/ARIA-tools/blob/dev/tools/ARIAtools/extractProduct.py#L901-L907

As a test, I ran
```
ariaExtract.py -f "products/*.nc" -w 9arc -l coherence -ml 3
```
on a small dataset (`ariaDownload.py -t 121 -b "30.5 36.5 85.3 90.3" -s 20180101 -e 20180401`)

and received the following message:
```
...
Thread count specified for gdal multiprocessing = 2
/home/rzinke/miniconda3/envs/ARIA-tools/lib/python3.10/site-packages/shapely/set_operations.py:133: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)
Rejected scene 9arc/productBoundingBox/20180420_20180114.json has no common overlap with bbox
1 out of 29 interferograms rejected for not meeting specified spatial thresholds
Generating: coherence - [=>                       4%                       ] 20180102_20161126    0s /     0sHDF5-DIAG: Error detected in HDF5 (1.12.2) thread 1:
  #000: H5A.c line 528 in H5Aopen_by_name(): can't open attribute
    major: Attribute
    minor: Can't open object
  #001: H5VLcallback.c line 1091 in H5VL_attr_open(): attribute open failed
    major: Virtual Object Layer
    minor: Can't open object
  #002: H5VLcallback.c line 1058 in H5VL__attr_open(): attribute open failed
    major: Virtual Object Layer
    minor: Can't open object
  #003: H5VLnative_attr.c line 130 in H5VL__native_attr_open(): can't open attribute
    major: Attribute
    minor: Can't open object
  #004: H5Aint.c line 545 in H5A__open_by_name(): unable to load attribute info from object header
    major: Attribute
    minor: Unable to initialize object
  #005: H5Oattribute.c line 494 in H5O__attr_open_by_name(): can't locate attribute: '_QuantizeBitGroomNumberOfSignificantDigits'
    major: Attribute
    minor: Object not found
HDF5-DIAG: Error detected in HDF5 (1.12.2) thread 1:
  #000: H5A.c line 528 in H5Aopen_by_name(): can't open attribute
    major: Attribute
    minor: Can't open object
  #001: H5VLcallback.c line 1091 in H5VL_attr_open(): attribute open failed
    major: Virtual Object Layer
    minor: Can't open object
  #002: H5VLcallback.c line 1058 in H5VL__attr_open(): attribute open failed
    major: Virtual Object Layer
    minor: Can't open object
  #003: H5VLnative_attr.c line 130 in H5VL__native_attr_open(): can't open attribute
    major: Attribute
    minor: Can't open object
  #004: H5Aint.c line 545 in H5A__open_by_name(): unable to load attribute info from object header
    major: Attribute
    minor: Unable to initialize object
  #005: H5Oattribute.c line 494 in H5O__attr_open_by_name(): can't locate attribute: '_QuantizeGranularBitRoundNumberOfSignificantDigits'
    major: Attribute
    minor: Object not found
```

**Comment by dbekaert** [comment]
@sssangha Can you look into this?

Please also work with @cmarshak to add a simple unit test that checks at the end of the aria-ts-setup that each of the dimensions is the same between all the variables.

**Comment by sssangha** [comment]
Hello @rzinke , just following up on our convo please make sure to re-test this off of our latest dev branch and specify a fresh `-w` work directory in your test.

Also @dbekaert I had added a check within the [export_product class ](https://github.com/aria-tools/ARIA-tools/blob/dev/tools/ARIAtools/extractProduct.py#L1181-L1193) to track and ensure consistency of dimensions.

**Comment by rzinke** [comment]
When I revert to an earlier commit (438e3e6) I do not encounter this issue for the same data sets. It must have been introduced sometime between then and the latest commit.

Enforcing same dimensions does not fix the issue, as the non-multilooked images simply get cropped.

**Comment by sssangha** [comment]
@rzinke I think I understand now.. So unless you specify an output format (e.g. `-of ISCE` or `-of ENVI`), then the program by default only passes VRTs for non interferometric layers where extraction is not necessary (e.g. coherence and amplitude). However, if a user specifies looks as you did then this behavior should be overridden and the layers physically extracted. I'm working on a patch now.
