### ISSUE TITLE
Proposal to change lisence for ARIA-tools and ARIA-tools-docs

### ISSUE THREAD

**Issue by dbekaert** [aria-tools/ARIA-tools#355]
# Proposal: Change GPL-3.0 license to Apache 2 license,

ARIA-tools and ARIA-tools-docs developers,

This repository is currently licensed under the terms and conditions of the [GPL-3.0 license](https://www.gnu.org/licenses/gpl-3.0.en.html). GPL-3.0 is copy-left which requires downstream projects to use the same license, prohibits commercial use, and is not the general direction which NASA is moving towards with open-science/TOPS.  

We would like to change the license from GNU-3 to Apache  2 in order to align with NASA open-science/ TOPS guidance and be less restrictive to downstream projects.

Contributors are tagged into this issue ticket and were reached out via email on 23 March 2023.

# Contributor responses:
| Contributor  | response |  github/email - Date recorded|
| ------------- | ------------- |------------- |
| @sssangha  |   approved          |   comment - 23 March 2023     |
| @dbekaert |   approved          |   comment - 23 March 2023     |
| @bbuzz31  |   approved          |   comment - 23 March 2023     |
| @ehavazli |   approved          |   comment - 23 March 2023     |
| @rzinke  | approved   | comment - 23 March 2023   |
| @yunjunz |    approved                       |      comment - 23 March 2023    |
| @mgovorcin |     approved          |   comment - 23 March 2023     |
| @cmarshak  |     approved                       |      comment - 23 March 2023    |
| @scottstanie |    approved                       |       comment - 23 March 2023             |
| @jhkennedy  |  approved                       |      comment - 23 March 2023    |
| @alexdunnjpl |  approved          |   comment - 23 March 2023     |
| @Askaholic  |    approved                       |      comment - 23 March 2023    |
| @jlmaurer |     approved          |   comment - 23 March 2023     |

**Comment by dbekaert** [comment]
@dbekaert  approved

**Comment by jhkennedy** [comment]
@jhkennedy approved!

**Comment by scottstanie** [comment]
@scottstanie approved

**Comment by ehavazli** [comment]
@ehavazli approved

**Comment by Askaholic** [comment]
@Askaholic approved

**Comment by yunjunz** [comment]
@yunjunz approved

**Comment by cmarshak** [comment]
Interesting that conda doesn't allow for GNU share-alike licences (or as wikipedia calls it, copyleft). I don't know how open source developers sue companies because they copyrighted derivative software. Who would pay the legal fees? Who would get the money? And does NASA have any private investment where they would benefit monetarily if they privatized open source software? (rhetorical questions)

**Comment by cmarshak** [comment]
I approve (though I just was a sounding board to Sim on one PR so my opinion shouldn't matter one iota).

**Comment by sssangha** [comment]
@sssangha approved

**Comment by mgovorcin** [comment]
@mgovorcin approved

**Comment by alexdunnjpl** [comment]
Rubber-stamp from me (approved)

**Comment by jlmaurer** [comment]
@jlmaurer approved!

**Comment by bbuzzanga** [comment]
@bbuzz31 approved

**Comment by rzinke** [comment]
approved!

**Comment by jhkennedy** [comment]
I have both:
* Released ARIA-Tools v1.1.5 which only differs from v1.1.4 in the license used
* Merged the license change into the ARIA-Tools `dev` branch so that the change should be applied going forward.

**Comment by jhkennedy** [comment]
I have also: 
* Released ARIA-Tools-docs v1.0.2 which only differs from v1.0.1 in the license used
* Merged the license change into the ARIA-Tools-docs `master` branch so that the change should be applied going forward.

This can now be considered done.
