### ISSUE TITLE
[BUG] Can the ariaExtract.py merge the  adjacent track or frame?

### ISSUE THREAD

**Issue by gaiyf** [aria-tools/ARIA-tools#374]
Hello everyone, I am newer to ARIA, and I wonder to know how to merge the adjacent track/frame.  just as the three pictures are shown on the homepage.

**Comment by mgovorcin** [comment]
Hi @gaiyf , **aria_tools** does the stitching of adjacent frames along the same track automatically. You can use either 
- ariaExtract.py - https://github.com/aria-tools/ARIA-tools-docs/blob/master/JupyterDocs/ariaExtract/ariaExtract_tutorial.ipynb
- ariaTSprep.py - https://github.com/aria-tools/ARIA-tools-docs/blob/master/JupyterDocs/ariaTSsetup/ariaTSsetup_tutorial.ipynb

However merging adjacent tracks is not supported. This requires both timeseries processing (e.g. using MIntpy) and re-referencing to the same reference frame for each processed tracks. 

Simple workflow would be: 
ARIAtools                        MINTPY                                                                      MINTPY
ariaTSprep.py > prep_aria > smallbaseline.py .... repeat for each track > image_stitch.py
However, note that with image_stitch.py from Mintpy does not take into account long-wavelength signal that will propage to you stitched solution and cause long ramp.

Hope this helps
