### ISSUE TITLE
[BUG] HDF5 error in ariaTSsetup processing

### ISSUE THREAD

**Issue by EJFielding** [aria-tools/ARIA-tools#384]
**Describe the bug**
I am getting some diagnostic error messages from the HDF5 (1.12.2) library when running ariaTSsetup.

**To Reproduce**
1. Download (ariaDownload.py -b '37.0 38.3 -122.6 -121.75' --track 42 --num_threads 8)
2. Command used (ariaTSsetup.py -f 'products/*.nc' -b '37.25 38.1 -122.6 -121.75' --mask Download --num_threads 8 --verbose)
3. Error Output:
```
Generating: coherence - 
HDF5-DIAG: Error detected in HDF5 (1.12.2) thread 1:
  #000: H5A.c line 528 in H5Aopen_by_name(): can't open attribute
    major: Attribute
    minor: Can't open object
  #001: H5VLcallback.c line 1091 in H5VL_attr_open(): attribute open failed
    major: Virtual Object Layer
    minor: Can't open object
  #002: H5VLcallback.c line 1058 in H5VL__attr_open(): attribute open failed
    major: Virtual Object Layer
    minor: Can't open object
  #003: H5VLnative_attr.c line 130 in H5VL__native_attr_open(): can't open attribute
    major: Attribute
    minor: Can't open object
  #004: H5Aint.c line 545 in H5A__open_by_name(): unable to load attribute info from object header
    major: Attribute
    minor: Unable to initialize object
  #005: H5Oattribute.c line 494 in H5O__attr_open_by_name(): can't locate attribute: '_QuantizeBitGroomNumberOfSignificantDigits'
    major: Attribute
    minor: Object not found

```

**Expected behavior**
There are hundreds of these errors for the hundreds of interferograms I have. The processing continues despite the errors or warnings.

**Desktop (please complete the following information):**
 - ARIA-tools git tag: [e.g. git show --summary]
 ```
 - commit 32018d59312f0267e077aba1e16de4f1c70a98d9 (HEAD -> dev, origin/dev, origin/HEAD)
Merge: 35c01cd 60ea380
Author: BB <bbuzz318@icloud.com>
Date:   Wed Sep 6 13:48:34 2023 -0700

    Merge pull request #381 from aria-tools/sss_latsortbug

    Sort pairs by latitude
```
 - OS Linux
 - python --version
Python 3.11.3

**Additional context**

**Comment by alexfore** [comment]
These errors looks like an HDF / filesystem issue
