### ISSUE TITLE
AriaTSsetup / I am using open science lab.

### ISSUE THREAD

**Issue by Nourmain** [aria-tools/ARIA-tools#385]

**Comment by bbuzzanga** [comment]
can you let us know if `./DEM/SRTM_3arcsec_uncropped.tif` exists (make sure relative to your current directory) and what is in it?

**Comment by Nourmain** [comment]
Hi. Yes the  ./DEM/SRTM_3arcsec_uncropped.tif is the only file that is
existing in the DEM folder. I'm trying two boundingbox for two locations.
the first one give me in the  ./DEM/SRTM_3arcsec_uncropped.tif this image
after download it:

[image: image.png]

for the second location , the  ./DEM/SRTM_3arcsec_uncropped.tif is only
exists in the DEM folder but windows photo viewer can't open it.

Thanks

**Comment by bbuzzanga** [comment]
Please open the file with a text file and report what it says. The image is not attached

**Comment by bbuzzanga** [comment]
Your API cannot be found. It looks like you're running aria-tools on open science lab, not on your locals windows. Probably your api key is in the wrong place. it should be stored in `/home/jovyan/.topoapi`

**Comment by Nourmain** [comment]
Yes I am using open science lab . How can I store the api key .
please help.

Thanks

**Comment by bbuzzanga** [comment]
Follow the instructions in the EarthScope materials or here: https://github.com/aria-tools/ARIA-tools-docs/blob/master/JupyterDocs/ariaExtract/ariaExtract_tutorial.ipynb

**Comment by bbuzzanga** [comment]
either the contents of the `~/.topoapi` are formatted incorrectly or you have a problem with it's location
