### ISSUE TITLE
[BUG]ariaExtract.py: Command not found

### ISSUE THREAD

**Issue by Suansuan0922** [aria-tools/ARIA-tools#386]
**Describe the bug**
When I use ariaExtract.py an error has occurred：
![2023-11-22 17-12-50 的屏幕截图](https://github.com/aria-tools/ARIA-tools/assets/147323171/ecb6cf5a-7324-4633-b180-65b41c6926c4)

but I have installed aria-tools:

Requirement already satisfied: ariatools in ./ARIA-tools/tools (1.1.6)

**Comment by bbuzzanga** [comment]
Please post the error in English. Also let us know how you installed ARIA-tools and what type of machine you are working on

**Comment by alexfore** [comment]
closing this due to lack of information
