### ISSUE TITLE
Set asf timeout on command line in ariaDownload.py

### ISSUE THREAD

**Issue by feigl** [aria-tools/ARIA-tools#388]
When running the following command, I receive the error message below. For the future, would you please consider adding a switch to set the timeout value on the command line interface? Such an option worked well in the past when using the SSARA federated query.

ariaDownload.py -v --bbox '40.3480000000 40.4490000000 -119.4600000000 -119.350' --output Download --start 20160101 --end 20230901 --track 137 -nt 30 -w ./products

Error Message: Connection Error (Timeout): CMR took too long to respond. Set asf constant "CMR_TIMEOUT" to increase. (url='https://cmr.earthdata.nasa.gov/search/granules.umm_json', timeout=30)
User Agent: Python/3.11.6; requests/2.31.0; asf_search/6.7.1     
Search Options: {
        intersectsWith: POLYGON ((-119.4599999999999937 40.4489999999999981, -119.4599999999999937 40.3479999999999990, -119.3499999999999943 40.3479999999999990, -119.3499999999999943 40.4489999999999981, -119.4599999999999937 40.4489999999999981))
        platform: ['SENTINEL-1A', 'SENTINEL-1B']
        processingLevel: ['GUNW_STD']
        relativeOrbit: [137]
}
"If you have any questions email uso@asf....

https://github.com/search?q=repo%3Aasfadmin%2FDiscovery-asf_search+CMR_TIMEOUT&type=code
ASF_AUTH_HOST = 'auth.asf.alaska.edu'
CMR_HOST = 'cmr.earthdata.nasa.gov'
CMR_TIMEOUT = 30
CMR_FORMAT_EXT = 'umm_json'
CMR_GRANULE_PATH = f'/search/granules.{CMR_FORMAT_EXT}'
CMR_COLLECTIONS = f'/search/collections'

**Comment by bbuzzanga** [comment]
@jhkennedy @Alex-lewandowski bringing this to your attention

**Comment by mgovorcin** [comment]
closing this issue as it is related to asf_search
