### ISSUE TITLE
import pkg_resources raises DeprecationWarning

### ISSUE THREAD

**Issue by alexfore** [aria-tools/ARIA-tools#414]
Two related issues:
* The import of pkg_resources raises DeprecationWarning.
* We should be able to use this software without having to install it
We need to find an alternative to pkg_resources and figure out how to make it not raise an Exception if it is not installed (i.e. if imported directly from the source repo)

**Comment by alexfore** [comment]
See this branch: https://github.com/aria-tools/ARIA-tools/compare/issue_414?expand=1

**Comment by dbekaert** [comment]
Awesome that looks much more transparent.

**Comment by alexfore** [comment]
closed by https://github.com/aria-tools/ARIA-tools/pull/415
