### ISSUE TITLE
[BUG] Argument missing when extracting solid Earth tide layer

### ISSUE THREAD

**Issue by rzinke** [aria-tools/ARIA-tools#426]
**Describe the bug**
I am attempting to extract the solid Earth tide layer from ARIA v. 3.0.1 products using ariaExtract.py. When I do, I get the error messge:

```
TypeError: handle_epoch_layers() missing 1 required positional argument: 'dem_bounds'
```

**To Reproduce**
1. Download 
```
ariaDownload.py -t 124 -w products --ifg 20180408_20180502 --version '3_0_1' -v 
```

2. Command used
```
ariaExtract.py -f "./products/*.nc" -l solidEarthTide
```

3. Error Output
```
Traceback (most recent call last):
  File "/opt/miniconda3/envs/ARIA-tools/bin/ariaExtract.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Users/rzinke/Tools/ARIA-tools/tools/bin/ariaExtract.py", line 285, in <module>
    main()
  File "/Users/rzinke/Tools/ARIA-tools/tools/bin/ariaExtract.py", line 272, in main
    arrshape = ARIAtools.extractProduct.export_products(**export_dict)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rzinke/Tools/ARIA-tools/tools/ARIAtools/extractProduct.py", line 1249, in export_products
    handle_epoch_layers(**lyr_input_dict)
TypeError: handle_epoch_layers() missing 1 required positional argument: 'dem_bounds'
```

**Desktop (please complete the following information):**
 - ARIA-tools git tag: db38bace50032925d2d5999ae970d74a5c1c541f (#425)
 - OS MacOS Sonoma 14.5

**Additional context**
Developing solid Earth tide layer extraction for ariaExtract_tutorial notebook in ARIA-tools-docs.

**Comment by sssangha** [comment]
@rzinke , currently traveling so it's hard to debug but I'm pretty sure this is because a valid DEM isn't specified (i.e. no valid path nor `download`).

Please confirm this, but that said maybe we should treat this issue a bit better. I.e. if we need to extract a metadata layer like SET, iono, tropo, or the geometry layers, exit before anything is done if a DEM isn't specified and provide a message that makes it clear why the code isn't working. Makes sense? Can you support this?

Thanks!

**Comment by rzinke** [comment]
I'll try specifying a valid DEM.
If that works then, I agree, AT should exit early in the process after checking the inputs.
I'll take a look now and update.

**Comment by rzinke** [comment]
I issued [PR427](https://github.com/aria-tools/ARIA-tools/pull/427) for this. Please have a look to test that it works and that the code format is aligned with the A-T code base. I wrote the function into `ariaExtract main()` because (1) ariaTSsetup already requires a DEM; and (2) utils.vrt.layerCheck would require a new input to accommodate this check.
