### ISSUE TITLE
Option to create DEM file for IFG extent

### ISSUE THREAD

**Issue by dbekaert** [aria-tools/ARIA-tools#64]
We generate a DEM for downloading products, the DEM over the IFG extend is only kept in memory. Suggest of adding an option to extract and store the IFG DEM as well.

@sssangha,  what would be the best place to put it?
All the products in folders are on the final bounding box.
We could make a folder with the DEM, but want to avoid users being confused by the SRTM dem at the top level. Alternatively we put all in a DEM folder and rename the original DEM with an uncropped suffix like we do for the coherence?

**Comment by ehavazli** [comment]
@dbekaert is this going to be different than what is done now? We are downloading a DEM automatically unless stated otherwise.

**Comment by dbekaert** [comment]
yes, it will be doing two DEM's one like we already have, the other on the productBoundingBox.

**Comment by dbekaert** [comment]
@sssangha has added this, closing this issues.
