### ISSUE TITLE
Jupyter notebook for Baseline and quality control plots 

### ISSUE THREAD

**Issue by dbekaert** [aria-tools/ARIA-tools#7]
Jupyter notebook which provides example on how to generate the quality and baseline plots for the GUNW products.
This is handled by the productPlot.py program.

Note book overview:

1) example of productPlot.py inputs and how to retrieve the help for it
Discuss the capabilities of the program:
- The program will figure out spatial-temporal continuous data sets, and plots are made per IFG or for an IFG pair.
- Explain the plotting options and which have more relevance for e.g. qualitative evaluation. e.g. coherence versus time, baseline plot color-coded with average coherence.

2-XXX) provide an example of each plotting option and explain what is happening or what can be observed. Include an example on how to use a mask file and detail how a mask file is used (i.e. 0/1 being masked etc)

**Comment by dbekaert** [comment]
updating all outputs of ariaPlot to go into figures. 
Will update notebook to reflect these changes.

**Comment by sssangha** [comment]
David, the commit I pushed yesterday already made it so that all outputs from ariaPlot go into "figures"

**Comment by dbekaert** [comment]
yes i saw,  but i needed to update the ariaPlot jupyter notebook to also capture that.
That has been completed now.
