### ISSUE TITLE
conflicts in requirements

### ISSUE THREAD

**Issue by dbekaert** [aria-tools/ARIA-tools#71]
Adding this issue ticket to sort out conflicts in the installation from the requirements file, given there were issues reported on slack with the installation.

 @piyushrpt is planning on doing an installation webinar next week.
So @ehavazli @bbuzz31 trying to get closure on the following and also confirm that it fixes issues you had before. Can you decribe here what the problems are?

Also, looking for the following changes:
1) update the GDAL basics notebook to remove the basemap dependency. I heard that basemap fixed the incompatibilities but not on the main branch, so it might be in sync by the course start, but unlikely by the installation demo. Given currently only 1 figure needs this dependency in a notebook not the tools i think we should just update the plotting from the GDAL notebook similar to the extract notebook.

2) Once item 1 is done update the requirements file to remove basemap dependencies.
- basemap
- basemap-data-hires

3) where there issues with the conda update, hdf5 etc?

**Comment by hfattahi** [comment]
adding @yunjunz as he is trying to install ARIA tools followed by MintPy installation. He seems to be seeing inconsistency between h5py and gdal3.0 which are both needed for running prep_aria.py in MintPy.

**Comment by yunjunz** [comment]
I had a hdf5 version conflict below while trying to install h5py to be able to run `prep_aria.py` in MintPy, after installing ARIA-tools.

```
(ARIA-tools) [yunjunz:~] yunjunz% conda install h5py
Collecting package metadata (current_repodata.json): done
Solving environment: failed with current_repodata.json, will retry with next repodata source.
Initial quick solve with frozen env failed.  Unfreezing env and trying again.
Solving environment: failed with current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed
Initial quick solve with frozen env failed.  Unfreezing env and trying again.
Solving environment: failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Package hdf5 conflicts for:
h5py -> hdf5[version='1.8.17|1.8.17.*,1.8.18|1.8.18.*,>=1.10.1,<1.10.2.0a0,>=1.10.4,<1.10.5.0a0,>=1.10.4,<1.10.5.0a0',build=mpi_mpich_*]
hdf5
kealib -> hdf5[version='1.8.17.*,1.8.17|1.8.17.*,>=1.10.2,<1.10.3.0a0,>=1.10.3,<1.10.4.0a0,>=1.10.4,<1.10.5.0a0,>=1.8.18,<1.8.19.0a0']
netcdf4 -> hdf5[version='1.10.1,1.8.18|1.8.18.*,>=1.10.1,<1.10.2.0a0,>=1.10.2,<1.10.3.0a0,>=1.10.3,<1.10.4.0a0,>=1.8.18,<1.8.19.0a0']
libgdal -> kealib[version='>=1.4.10,<1.5.0a0,>=1.4.7,<1.5.0a0'] -> hdf5[version='>=1.10.2,<1.10.3.0a0,>=1.10.4,<1.10.5.0a0,>=1.8.18,<1.8.19.0a0']
```

Using pip from conda, instead of conda directly, solved the problem, as suggested by @ehavazli:

```
pip install h5py
```

**Comment by ehavazli** [comment]
>     1. update the GDAL basics notebook to remove the basemap dependency. I heard that basemap fixed the incompatibilities but not on the main branch, so it might be in sync by the course start, but unlikely by the installation demo. Given currently only 1 figure needs this dependency in a notebook not the tools i think we should just update the plotting from the GDAL notebook similar to the extract notebook.
> 
>     2. Once item 1 is done update the requirements file to remove basemap dependencies.
> 
> 
>     * basemap
> 
>     * basemap-data-hires

I will get this done.




>     1. where there issues with the conda update, hdf5 etc?

the problem arises when conda makes changes to GDAL versions. It is important to be aware that a similar issue like h5py can arise with other packages as well. Every now and then I make tests with installation from scratch and after h5py problem, I had had issues with numpy. However, all these issues are going to be resolved hopefully as conda stabilizes packages. Until then, if there is a problem with a package pip is useful to overcome the issue.

**Comment by dbekaert** [comment]
@piyushrpt mentioned to try and force h5py<1.10.5 in the conda requirements.

**Comment by piyushrpt** [comment]
You should use hdf5 < 1.10.5 - if you have a dependency on h5py for now. They are still evaluating upgrading to 1.10.5.

**Comment by yunjunz** [comment]
Adding `hdf5<1.10.5` and `h5py` to requirements.txt still give me the same conflicts as before.

```
[yunjunz:~] yunjunz% conda install -n ARIA-tools --file $ARIATOOLS_HOME/requirements.txt 
```

**Comment by piyushrpt** [comment]
@yunjunz . I tried the same just now but with "-c conda-forge" and everything works as expected. GDAL 3 is only available on available on forge I believe.

**Comment by rzinke** [comment]
I am also trying to install ARIA-tools and MintPy on the same machine, in different conda environments. To get the prep_aria.py script working, while keeping my ARIA-tools and MintPy environments intact, I am attempting to create a "hybrid" conda environment with both gdal 3 and h5py installed. However,

conda create -n Hybrid --file ~/tools/ARIA-tools/requirements_plus.txt --yes -c conda-forge

results in an error: 
Solving environment: failed
UnsatisfiableError: The following specifications were found to be incompatible with each other:
Package hdf5 conflicts for:
netcdf4 -> libnetcdf[version='4.4.*,>=4.5,>=4.6.1,<4.7.0a0,>=4.6.1,<5.0a0'] -> hdf5[version='1.10.1,1.8.17|1.8.17.*,>=1.10.1,<1.10.2.0a0,>=1.8.18,<1.8.19.0a0,>=1.8.20,<1.9.0a0']
hdf5[version='<1.10.5']

The "requirements_plus.txt" has "hdf5" added and "basemap", "basemap-data-hires" commented out.

**Comment by rzinke** [comment]
To follow up on the previous post, hdf5 v 1.10.5 was installed. However, when I run the prep_aria.py script it reports "No module named h5py". When I try conda install h5py, it reports conflicts with gdal 3, among other packages.

**Comment by piyushrpt** [comment]
h5py and packages that require HDF5 > 1.10.4 cannot coexist for now. h5py-feedstock hasn't been updated and their evaluation of 1.10.5 is in progress.  I dont think GDAL 3 -> HDF5 1.10.4 is available. You will have to use different environments for these. 

See: https://github.com/conda-forge/h5py-feedstock/issues/52

**Comment by piyushrpt** [comment]
Alternately, you can try installing gdal3 and then h5py using pip using the HDF5 that GDAL provided you with.

**Comment by rzinke** [comment]
Thanks @piyushrpt. Using pip install h5py looks like it worked! It appears it installed on top of gdal's hdf5 and they are compatible.

**Comment by ehavazli** [comment]
> Using pip from conda, instead of conda directly, solved the problem, as suggested by @ehavazli:
> 
> ```
> pip install h5py
> ```

@rzinke currently pip is working fine. I will update the requirements.txt when dependencies are consistent with each other (or not but will include appropriate recommendations).

**Comment by dbekaert** [comment]
@yunjunz is there a way to specify directly a pip install in the requirements directly?
I did some searching and believe there is not.

**Comment by dbekaert** [comment]
Item 1 and 2 are closed. will await feedback to see if we can do pip directly from requirements alternatively will update the README to use pip after conda install of requirements.

>     1. update the GDAL basics notebook to remove the basemap dependency. I heard that basemap fixed the incompatibilities but not on the main branch, so it might be in sync by the course start, but unlikely by the installation demo. Given currently only 1 figure needs this dependency in a notebook not the tools i think we should just update the plotting from the GDAL notebook similar to the extract notebook.
> 
>     2. Once item 1 is done update the requirements file to remove basemap dependencies.
> 
> 
>     * basemap
> 
>     * basemap-data-hires
> 
> 
>     3. where there issues with the conda update, hdf5 etc?

**Comment by ehavazli** [comment]
@dbekaert 
Today I made tests by removing basemap and adding cartopy. It seems like everything else is in place for ARIA-tools. There were no conflicts (at least for today)

**Comment by yunjunz** [comment]
> @yunjunz is there a way to specify directly a pip install in the requirements directly?
> I did some searching and believe there is not.

@dbekaert not I am aware of.

**Comment by yunjunz** [comment]
@dbekaert it's doable using *.yml file and explained here:
https://github.com/CellProfiler/CellProfiler/wiki/Conda-Installation

**Comment by dbekaert** [comment]
@yunjunz great, yeah that looks like a good way of doing it.

**Comment by dbekaert** [comment]
this is now resolved
